<code id="aboutPageCode"><!-- HTML generated using hilite.me --><div style="background: #272822; overflow:auto;width:auto;border:none;border-width:.1em .1em .1em .8em;padding:.2em .6em;"><pre style="margin: 0; line-height: 125%"><span style="color: #75715e">&lt;?php</span> <span style="color: #66d9ef">include</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;phpIncludes/header_nav.php&quot;</span><span style="color: #f8f8f2">)</span> <span style="color: #75715e">?&gt;</span>


<span style="color: rgb(231, 95, 85)">&lt;section</span> <span style="color: #a6e22e">id=</span><span style="color: #e6db74">&quot;cinecoptersAbout&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>

<span style="color: rgb(231, 95, 85)">&lt;div</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;imgContainer&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
      <span style="color: rgb(231, 95, 85)">&lt;div</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">bgImg</span><span style="color: rgb(231, 95, 85)">&gt;</span>
        <span style="color: rgb(231, 95, 85)">&lt;div</span> <span style="color: #a6e22e">id=</span><span style="color: #e6db74">&quot;title&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
          <span style="color: rgb(231, 95, 85)">&lt;h2&gt;</span>WHO WE ARE<span style="color: rgb(231, 95, 85)">&lt;/h2&gt;</span>
        <span style="color: rgb(231, 95, 85)">&lt;/div&gt;</span>
          <span style="color: rgb(231, 95, 85)">&lt;div</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;aboutText&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;p&gt;</span>CineCopters, founded in 2013, brings Belfast, Northern Ireland, Ireland and the UK a higher standard of aerial drone filming.
            <span style="color: rgb(231, 95, 85)">&lt;br&gt;&lt;br&gt;</span>     ​
            One of the industry leaders and BBC preferred supplier in aerial cinematography we bring together state-of-the-art light and heavy lift aerial drone technology, the latest digital 4K-8K RAW HD cinema cameras, zero delay HD video transmission, advanced gimbal technology and a group of highly dedicated professionals together with over 50 years hands on film and television experience.
            <span style="color: rgb(231, 95, 85)">&lt;br&gt;&lt;br&gt;</span>
            Our knowledge in the entertainment, film, television, engineering and radio controlled world allows us to provide a new dimension for productions requiring a high-end look at an affordable price.
            <span style="color: rgb(231, 95, 85)">&lt;br&gt;&lt;br&gt;&lt;br&gt;</span>
            We know how this works, we make life easy.<span style="color: rgb(231, 95, 85)">&lt;/p&gt;</span>
                
                <span style="color: rgb(231, 95, 85)">&lt;div</span> <span style="color: #a6e22e">id=</span><span style="color: #e6db74">&quot;aboutBounceBtn&quot;</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;arrow bounce&quot;</span><span style="color: rgb(231, 95, 85)">&gt;&lt;i</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;fa fa-angle-down fa-3x&quot;</span> <span style="color: #a6e22e">aria-hidden=</span><span style="color: #e6db74">&quot;true&quot;</span><span style="color: rgb(231, 95, 85)">&gt;&lt;/i&gt;&lt;/div&gt;</span>
        <span style="color: rgb(231, 95, 85)">&lt;/div&gt;</span>
      <span style="color: rgb(231, 95, 85)">&lt;/div&gt;</span>
    <span style="color: rgb(231, 95, 85)">&lt;/div&gt;</span>







<span style="color: rgb(231, 95, 85)">&lt;div</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;container&quot;</span> <span style="color: #a6e22e">id=</span><span style="color: #e6db74">&quot;imgGalleryWrapper&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
	<span style="color: rgb(231, 95, 85)">&lt;div</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;row&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
		<span style="color: rgb(231, 95, 85)">&lt;div</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;row&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;div</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;col-lg-3 col-md-4 col-xs-6 thumb&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;a</span> <span style="color: #a6e22e">id=</span><span style="color: #e6db74">&quot;redbullHandset&quot;</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;thumbnail&quot;</span> <span style="color: #a6e22e">href=</span><span style="color: #e6db74">&quot;#&quot;</span> <span style="color: #a6e22e">data-image-id=</span><span style="color: #e6db74">&quot;&quot;</span> <span style="color: #a6e22e">data-toggle=</span><span style="color: #e6db74">&quot;modal&quot;</span> <span style="color: #a6e22e">data-title=</span><span style="color: #e6db74">&quot;CineCopters - RedBull F1&quot;</span>
                   <span style="color: #a6e22e">data-image=</span><span style="color: #e6db74">&quot;/img/_DSC0133.jpg&quot;</span>
                   <span style="color: #a6e22e">data-target=</span><span style="color: #e6db74">&quot;#image-gallery&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                    <span style="color: rgb(231, 95, 85)">&lt;img</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;img-thumbnail&quot;</span><span style="color: #a6e22e">src=</span><span style="color: #e6db74">&quot;/img/_DSC0133.jpg&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;/a&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;/div&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;div</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;col-lg-3 col-md-4 col-xs-6 thumb&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;a</span> <span style="color: #a6e22e">id=</span><span style="color: #e6db74">&quot;imgTwo&quot;</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;thumbnail&quot;</span> <span style="color: #a6e22e">href=</span><span style="color: #e6db74">&quot;#&quot;</span> <span style="color: #a6e22e">data-image-id=</span><span style="color: #e6db74">&quot;&quot;</span> <span style="color: #a6e22e">data-toggle=</span><span style="color: #e6db74">&quot;modal&quot;</span> <span style="color: #a6e22e">data-title=</span><span style="color: #e6db74">&quot;CineCopters Halo - Nightfall | HeavyLift&quot;</span>
                   <span style="color: #a6e22e">data-image=</span><span style="color: #e6db74">&quot;/img/10627694_10152365249931633_738385052_o.jpg&quot;</span>
                   <span style="color: #a6e22e">data-target=</span><span style="color: #e6db74">&quot;#image-gallery&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                    <span style="color: rgb(231, 95, 85)">&lt;img</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;img-thumbnail&quot;</span><span style="color: #a6e22e">src=</span><span style="color: #e6db74">&quot;/img/10627694_10152365249931633_738385052_o.jpg&quot;</span>
                   <span style="color: #a6e22e">data-target=</span><span style="color: #e6db74">&quot;#image-gallery&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;/a&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;/div&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;div</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;col-lg-3 col-md-4 col-xs-6 thumb&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;a</span> <span style="color: #a6e22e">id=</span><span style="color: #e6db74">&quot;heavyTrolley&quot;</span><span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;thumbnail&quot;</span> <span style="color: #a6e22e">href=</span><span style="color: #e6db74">&quot;#&quot;</span> <span style="color: #a6e22e">data-image-id=</span><span style="color: #e6db74">&quot;&quot;</span> <span style="color: #a6e22e">data-toggle=</span><span style="color: #e6db74">&quot;modal&quot;</span> <span style="color: #a6e22e">data-title=</span><span style="color: #e6db74">&quot;CineCopters - Line of Duty 6&quot;</span>
                   <span style="color: #a6e22e">data-image=</span><span style="color: #e6db74">&quot;/img/vulcan5.png&quot;</span>
                   <span style="color: #a6e22e">data-target=</span><span style="color: #e6db74">&quot;#image-gallery&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                    <span style="color: rgb(231, 95, 85)">&lt;img</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;img-thumbnail&quot;</span><span style="color: #a6e22e">src=</span><span style="color: #e6db74">&quot;/img/vulcan5.png&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;/a&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;/div&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;div</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;col-lg-3 col-md-4 col-xs-6 thumb&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;a</span> <span style="color: #a6e22e">id=</span><span style="color: #e6db74">&quot;mercImg&quot;</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;thumbnail&quot;</span> <span style="color: #a6e22e">href=</span><span style="color: #e6db74">&quot;#&quot;</span> <span style="color: #a6e22e">data-image-id=</span><span style="color: #e6db74">&quot;&quot;</span> <span style="color: #a6e22e">data-toggle=</span><span style="color: #e6db74">&quot;modal&quot;</span> <span style="color: #a6e22e">data-title=</span><span style="color: #e6db74">&quot;CineCopters - Mercedes Commercial&quot;</span>
                   <span style="color: #a6e22e">data-image=</span><span style="color: #e6db74">&quot;/img/merc.jpg&quot;</span>
                   <span style="color: #a6e22e">data-target=</span><span style="color: #e6db74">&quot;#image-gallery&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                    <span style="color: rgb(231, 95, 85)">&lt;img</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;img-thumbnail&quot;</span><span style="color: #a6e22e">src=</span><span style="color: #e6db74">&quot;/img/merc.jpg&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;/a&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;/div&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;div</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;col-lg-3 col-md-4 col-xs-6 thumb&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;a</span> <span style="color: #a6e22e">id=</span><span style="color: #e6db74">&quot;cliffDivingImg&quot;</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;thumbnail&quot;</span> <span style="color: #a6e22e">href=</span><span style="color: #e6db74">&quot;#&quot;</span> <span style="color: #a6e22e">data-image-id=</span><span style="color: #e6db74">&quot;&quot;</span> <span style="color: #a6e22e">data-toggle=</span><span style="color: #e6db74">&quot;modal&quot;</span> <span style="color: #a6e22e">data-title=</span><span style="color: #e6db74">&quot;CineCopters - RedBull Cliff Diving&quot;</span>
                   <span style="color: #a6e22e">data-image=</span><span style="color: #e6db74">&quot;/img/tethered.jpg&quot;</span>
                   <span style="color: #a6e22e">data-target=</span><span style="color: #e6db74">&quot;#image-gallery&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                    <span style="color: rgb(231, 95, 85)">&lt;img</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;img-thumbnail&quot;</span><span style="color: #a6e22e">src=</span><span style="color: #e6db74">&quot;/img/tethered.jpg&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;/a&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;/div&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;div</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;col-lg-3 col-md-4 col-xs-6 thumb&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;a</span> <span style="color: #a6e22e">id=</span><span style="color: #e6db74">&quot;vulcan3&quot;</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;thumbnail&quot;</span> <span style="color: #a6e22e">href=</span><span style="color: #e6db74">&quot;#&quot;</span> <span style="color: #a6e22e">data-image-id=</span><span style="color: #e6db74">&quot;&quot;</span> <span style="color: #a6e22e">data-toggle=</span><span style="color: #e6db74">&quot;modal&quot;</span> <span style="color: #a6e22e">data-title=</span><span style="color: #e6db74">&quot;CineCopters - Heavylift with Red Epic&quot;</span>
                   <span style="color: #a6e22e">data-image=</span><span style="color: #e6db74">&quot;/img/vulcan3.jpg&quot;</span>
                   <span style="color: #a6e22e">data-target=</span><span style="color: #e6db74">&quot;#image-gallery&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                    <span style="color: rgb(231, 95, 85)">&lt;img</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;img-thumbnail&quot;</span><span style="color: #a6e22e">src=</span><span style="color: #e6db74">&quot;/img/vulcan3.jpg&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;/a&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;/div&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;div</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;col-lg-3 col-md-4 col-xs-6 thumb&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;a</span> <span style="color: #a6e22e">id=</span><span style="color: #e6db74">&quot;oldOcto&quot;</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;thumbnail&quot;</span> <span style="color: #a6e22e">href=</span><span style="color: #e6db74">&quot;#&quot;</span> <span style="color: #a6e22e">data-image-id=</span><span style="color: #e6db74">&quot;&quot;</span> <span style="color: #a6e22e">data-toggle=</span><span style="color: #e6db74">&quot;modal&quot;</span> <span style="color: #a6e22e">data-title=</span><span style="color: #e6db74">&quot;CineCopters - Heavylift Wicklow&quot;</span>
                   <span style="color: #a6e22e">data-image=</span><span style="color: #e6db74">&quot;/img/unnamed (1).jpg&quot;</span>
                   <span style="color: #a6e22e">data-target=</span><span style="color: #e6db74">&quot;#image-gallery&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                    <span style="color: rgb(231, 95, 85)">&lt;img</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;img-thumbnail&quot;</span><span style="color: #a6e22e">src=</span><span style="color: #e6db74">&quot;/img/unnamed (1).jpg&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;/a&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;/div&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;div</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;col-lg-3 col-md-4 col-xs-6 thumb&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;a</span> <span style="color: #a6e22e">id=</span><span style="color: #e6db74">&quot;handsetImg&quot;</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;thumbnail&quot;</span> <span style="color: #a6e22e">href=</span><span style="color: #e6db74">&quot;#&quot;</span> <span style="color: #a6e22e">data-image-id=</span><span style="color: #e6db74">&quot;&quot;</span> <span style="color: #a6e22e">data-toggle=</span><span style="color: #e6db74">&quot;modal&quot;</span> <span style="color: #a6e22e">data-title=</span><span style="color: #e6db74">&quot;CineCopters - Into The Badlands&quot;</span>
                   <span style="color: #a6e22e">data-image=</span><span style="color: #e6db74">&quot;/img/cinecopters handset.jpg&quot;</span>
                   <span style="color: #a6e22e">data-target=</span><span style="color: #e6db74">&quot;#image-gallery&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                    <span style="color: rgb(231, 95, 85)">&lt;img</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;img-thumbnail&quot;</span><span style="color: #a6e22e">src=</span><span style="color: #e6db74">&quot;/img/cinecopters handset.jpg&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;/a&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;/div&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;div</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;col-lg-3 col-md-4 col-xs-6 thumb&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;a</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;thumbnail&quot;</span> <span style="color: #a6e22e">href=</span><span style="color: #e6db74">&quot;#&quot;</span> <span style="color: #a6e22e">data-image-id=</span><span style="color: #e6db74">&quot;&quot;</span> <span style="color: #a6e22e">data-toggle=</span><span style="color: #e6db74">&quot;modal&quot;</span> <span style="color: #a6e22e">data-title=</span><span style="color: #e6db74">&quot;CineCopters Scotland Commerical&quot;</span>
                   <span style="color: #a6e22e">data-image=</span><span style="color: #e6db74">&quot;/img/inspire2x2.jpg&quot;</span>
                   <span style="color: #a6e22e">data-target=</span><span style="color: #e6db74">&quot;#image-gallery&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                    <span style="color: rgb(231, 95, 85)">&lt;img</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;img-thumbnail&quot;</span><span style="color: #a6e22e">src=</span><span style="color: #e6db74">&quot;/img/inspire2x2.jpg&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;/a&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;/div&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;div</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;col-lg-3 col-md-4 col-xs-6 thumb&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;a</span> <span style="color: #a6e22e">id=</span><span style="color: #e6db74">&quot;inspireRoofImg&quot;</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;thumbnail&quot;</span> <span style="color: #a6e22e">href=</span><span style="color: #e6db74">&quot;#&quot;</span> <span style="color: #a6e22e">data-image-id=</span><span style="color: #e6db74">&quot;&quot;</span> <span style="color: #a6e22e">data-toggle=</span><span style="color: #e6db74">&quot;modal&quot;</span> <span style="color: #a6e22e">data-title=</span><span style="color: #e6db74">&quot;CineCopters Belfast Rooftops&quot;</span>
                   <span style="color: #a6e22e">data-image=</span><span style="color: #e6db74">&quot;/img/inspire2roof.jpg&quot;</span>
                   <span style="color: #a6e22e">data-target=</span><span style="color: #e6db74">&quot;#image-gallery&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                    <span style="color: rgb(231, 95, 85)">&lt;img</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;img-thumbnail&quot;</span><span style="color: #a6e22e">src=</span><span style="color: #e6db74">&quot;/img/inspire2roof.jpg&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;/a&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;/div&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;div</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;col-lg-3 col-md-4 col-xs-6 thumb&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;a</span> <span style="color: #a6e22e">id=</span><span style="color: #e6db74">&quot;inspireWheelsImg&quot;</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;thumbnail&quot;</span> <span style="color: #a6e22e">href=</span><span style="color: #e6db74">&quot;#&quot;</span> <span style="color: #a6e22e">data-image-id=</span><span style="color: #e6db74">&quot;&quot;</span> <span style="color: #a6e22e">data-toggle=</span><span style="color: #e6db74">&quot;modal&quot;</span> <span style="color: #a6e22e">data-title=</span><span style="color: #e6db74">&quot;CineCopters Tourism Ireland Commercial&quot;</span>
                   <span style="color: #a6e22e">data-image=</span><span style="color: #e6db74">&quot;/img/inspirewheels.jpg&quot;</span>
                   <span style="color: #a6e22e">data-target=</span><span style="color: #e6db74">&quot;#image-gallery&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                    <span style="color: rgb(231, 95, 85)">&lt;img</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;img-thumbnail&quot;</span><span style="color: #a6e22e">src=</span><span style="color: #e6db74">&quot;/img/inspirewheels.jpg&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;/a&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;/div&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;div</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;col-lg-3 col-md-4 col-xs-6 thumb&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;a</span> <span style="color: #a6e22e">id=</span><span style="color: #e6db74">&quot;samlukeImg&quot;</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;thumbnail&quot;</span> <span style="color: #a6e22e">href=</span><span style="color: #e6db74">&quot;#&quot;</span> <span style="color: #a6e22e">data-image-id=</span><span style="color: #e6db74">&quot;&quot;</span> <span style="color: #a6e22e">data-toggle=</span><span style="color: #e6db74">&quot;modal&quot;</span> <span style="color: #a6e22e">data-title=</span><span style="color: #e6db74">&quot;CineCopters - The Other Lamb Feature Film&quot;</span>
                   <span style="color: #a6e22e">data-image=</span><span style="color: #e6db74">&quot;/img/67104411_2161695943929338_2577002939063205888_o.jpg&quot;</span>
                   <span style="color: #a6e22e">data-target=</span><span style="color: #e6db74">&quot;#image-gallery&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                    <span style="color: rgb(231, 95, 85)">&lt;img</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;img-thumbnail&quot;</span><span style="color: #a6e22e">src=</span><span style="color: #e6db74">&quot;/img/67104411_2161695943929338_2577002939063205888_o.jpg&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;/a&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;/div&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;div</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;col-lg-3 col-md-4 col-xs-6 thumb&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;a</span> <span style="color: #a6e22e">id=</span><span style="color: #e6db74">&quot;tommyjackImg&quot;</span> <span style="color: #a6e22e">id=</span><span style="color: #e6db74">&quot;samlukeImg&quot;</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;thumbnail&quot;</span> <span style="color: #a6e22e">href=</span><span style="color: #e6db74">&quot;#&quot;</span> <span style="color: #a6e22e">data-image-id=</span><span style="color: #e6db74">&quot;&quot;</span> <span style="color: #a6e22e">data-toggle=</span><span style="color: #e6db74">&quot;modal&quot;</span> <span style="color: #a6e22e">data-title=</span><span style="color: #e6db74">&quot;CineCopters - Dublin The Racer Feature Film&quot;</span>
                   <span style="color: #a6e22e">data-image=</span><span style="color: #e6db74">&quot;/img/64289138_2092715050827428_1283367366557696000_n.jpg&quot;</span>
                   <span style="color: #a6e22e">data-target=</span><span style="color: #e6db74">&quot;#image-gallery&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                    <span style="color: rgb(231, 95, 85)">&lt;img</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;img-thumbnail&quot;</span><span style="color: #a6e22e">src=</span><span style="color: #e6db74">&quot;/img/64289138_2092715050827428_1283367366557696000_n.jpg&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;/a&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;/div&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;div</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;col-lg-3 col-md-4 col-xs-6 thumb&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;a</span> <span style="color: #a6e22e">id=</span><span style="color: #e6db74">&quot;samlukeImg&quot;</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;thumbnail&quot;</span> <span style="color: #a6e22e">href=</span><span style="color: #e6db74">&quot;#&quot;</span> <span style="color: #a6e22e">data-image-id=</span><span style="color: #e6db74">&quot;&quot;</span> <span style="color: #a6e22e">data-toggle=</span><span style="color: #e6db74">&quot;modal&quot;</span> <span style="color: #a6e22e">data-title=</span><span style="color: #e6db74">&quot;CineCopters - Four Kids and IT Feature Film&quot;</span>
                   <span style="color: #a6e22e">data-image=</span><span style="color: #e6db74">&quot;/img/62471005_2085453454886921_2825154707633209344_n.jpg&quot;</span>
                   <span style="color: #a6e22e">data-target=</span><span style="color: #e6db74">&quot;#image-gallery&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                    <span style="color: rgb(231, 95, 85)">&lt;img</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;img-thumbnail&quot;</span><span style="color: #a6e22e">src=</span><span style="color: #e6db74">&quot;/img/62471005_2085453454886921_2825154707633209344_n.jpg&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;/a&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;/div&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;div</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;col-lg-3 col-md-4 col-xs-6 thumb&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;a</span> <span style="color: #a6e22e">id=</span><span style="color: #e6db74">&quot;inspirethreesixty&quot;</span> <span style="color: #a6e22e">id=</span><span style="color: #e6db74">&quot;samlukeImg&quot;</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;thumbnail&quot;</span> <span style="color: #a6e22e">href=</span><span style="color: #e6db74">&quot;#&quot;</span> <span style="color: #a6e22e">data-image-id=</span><span style="color: #e6db74">&quot;&quot;</span> <span style="color: #a6e22e">data-toggle=</span><span style="color: #e6db74">&quot;modal&quot;</span> <span style="color: #a6e22e">data-title=</span><span style="color: #e6db74">&quot;Belfast City Morning&quot;</span>
                   <span style="color: #a6e22e">data-image=</span><span style="color: #e6db74">&quot;/img/41725398_1708822982549972_8969894002031591424_n.jpg&quot;</span>
                   <span style="color: #a6e22e">data-target=</span><span style="color: #e6db74">&quot;#image-gallery&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                    <span style="color: rgb(231, 95, 85)">&lt;img</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;img-thumbnail&quot;</span><span style="color: #a6e22e">src=</span><span style="color: #e6db74">&quot;/img/41725398_1708822982549972_8969894002031591424_n.jpg&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;/a&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;/div&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;div</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;col-lg-3 col-md-4 col-xs-6 thumb&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;a</span> <span style="color: #a6e22e">id=</span><span style="color: #e6db74">&quot;samlukeImg&quot;</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;thumbnail&quot;</span> <span style="color: #a6e22e">href=</span><span style="color: #e6db74">&quot;#&quot;</span> <span style="color: #a6e22e">data-image-id=</span><span style="color: #e6db74">&quot;&quot;</span> <span style="color: #a6e22e">data-toggle=</span><span style="color: #e6db74">&quot;modal&quot;</span> <span style="color: #a6e22e">data-title=</span><span style="color: #e6db74">&quot;Belfast City Morning&quot;</span>
                   <span style="color: #a6e22e">data-image=</span><span style="color: #e6db74">&quot;/img/46434242_1794008174031452_5998442666663084032_n.jpg&quot;</span>
                   <span style="color: #a6e22e">data-target=</span><span style="color: #e6db74">&quot;#image-gallery&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                    <span style="color: rgb(231, 95, 85)">&lt;img</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;img-thumbnail&quot;</span><span style="color: #a6e22e">src=</span><span style="color: #e6db74">&quot;/img/46434242_1794008174031452_5998442666663084032_n.jpg&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;/a&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;/div&gt;</span>
            


        <span style="color: rgb(231, 95, 85)">&lt;div</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;modal fade&quot;</span> <span style="color: #a6e22e">id=</span><span style="color: #e6db74">&quot;image-gallery&quot;</span> <span style="color: #a6e22e">tabindex=</span><span style="color: #e6db74">&quot;-1&quot;</span> <span style="color: #a6e22e">role=</span><span style="color: #e6db74">&quot;dialog&quot;</span> <span style="color: #a6e22e">aria-labelledby=</span><span style="color: #e6db74">&quot;myModalLabel&quot;</span> <span style="color: #a6e22e">aria-hidden=</span><span style="color: #e6db74">&quot;true&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;div</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;modal-dialog modal-lg&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;div</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;modal-content&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                    <span style="color: rgb(231, 95, 85)">&lt;div</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;modal-header&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                        <span style="color: rgb(231, 95, 85)">&lt;h4</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;modal-title&quot;</span> <span style="color: #a6e22e">id=</span><span style="color: #e6db74">&quot;image-gallery-title&quot;</span><span style="color: rgb(231, 95, 85)">&gt;&lt;/h4&gt;</span>
                        <span style="color: rgb(231, 95, 85)">&lt;button</span> <span style="color: #a6e22e">type=</span><span style="color: #e6db74">&quot;button&quot;</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;close&quot;</span> <span style="color: #a6e22e">data-dismiss=</span><span style="color: #e6db74">&quot;modal&quot;</span><span style="color: rgb(231, 95, 85)">&gt;&lt;span</span> <span style="color: #a6e22e">aria-hidden=</span><span style="color: #e6db74">&quot;true&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>×<span style="color: rgb(231, 95, 85)">&lt;/span&gt;&lt;span</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;sr-only&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>Close<span style="color: rgb(231, 95, 85)">&lt;/span&gt;</span>
                        <span style="color: rgb(231, 95, 85)">&lt;/button&gt;</span>
                    <span style="color: rgb(231, 95, 85)">&lt;/div&gt;</span>
                    <span style="color: rgb(231, 95, 85)">&lt;div</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;modal-body&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                        <span style="color: rgb(231, 95, 85)">&lt;img</span> <span style="color: #a6e22e">id=</span><span style="color: #e6db74">&quot;image-gallery-image&quot;</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;img-responsive col-md-12&quot;</span> <span style="color: #a6e22e">src=</span><span style="color: #e6db74">&quot;&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                    <span style="color: rgb(231, 95, 85)">&lt;/div&gt;</span>
                    <span style="color: rgb(231, 95, 85)">&lt;div</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;modal-footer&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                        <span style="color: rgb(231, 95, 85)">&lt;button</span> <span style="color: #a6e22e">type=</span><span style="color: #e6db74">&quot;button&quot;</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;btn btn-secondary float-left&quot;</span> <span style="color: #a6e22e">id=</span><span style="color: #e6db74">&quot;show-previous-image&quot;</span><span style="color: rgb(231, 95, 85)">&gt;&lt;i</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;fa fa-arrow-left&quot;</span><span style="color: rgb(231, 95, 85)">&gt;&lt;/i&gt;</span>
                        <span style="color: rgb(231, 95, 85)">&lt;/button&gt;</span>

                        <span style="color: rgb(231, 95, 85)">&lt;button</span> <span style="color: #a6e22e">type=</span><span style="color: #e6db74">&quot;button&quot;</span> <span style="color: #a6e22e">id=</span><span style="color: #e6db74">&quot;show-next-image&quot;</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;btn btn-secondary float-right&quot;</span><span style="color: rgb(231, 95, 85)">&gt;&lt;i</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;fa fa-arrow-right&quot;</span><span style="color: rgb(231, 95, 85)">&gt;&lt;/i&gt;</span>
                        <span style="color: rgb(231, 95, 85)">&lt;/button&gt;</span>
                    <span style="color: rgb(231, 95, 85)">&lt;/div&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;/div&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;/div&gt;</span>
        <span style="color: rgb(231, 95, 85)">&lt;/div&gt;</span>
	<span style="color: rgb(231, 95, 85)">&lt;/div&gt;</span>
<span style="color: rgb(231, 95, 85)">&lt;/div&gt;</span>

<span style="color: rgb(231, 95, 85)">&lt;div</span> <span style="color: #a6e22e">id=</span><span style="color: #e6db74">&quot;qualis&quot;</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;container&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
    <span style="color: rgb(231, 95, 85)">&lt;h2&gt;</span>Qualifications<span style="color: rgb(231, 95, 85)">&lt;/h2&gt;</span>
    <span style="color: rgb(231, 95, 85)">&lt;p&gt;</span>CineCopters pilots are fully licensed, extensively trained, tested and regulated under the Resource UAS RPQ-s and Euro UCS BNUC-s licences’.  We uphold the regulations outlined by the CAA (Civil Aviation Authority) and the IAA (Irish Aviation Authority).
    <span style="color: rgb(231, 95, 85)">&lt;br&gt;&lt;br&gt;</span>
    These licenses as well as full insurance is a legal requirement in the UK and Europe to undertake commercial aerial work using unmanned aerial vehicles.
    <span style="color: rgb(231, 95, 85)">&lt;br&gt;&lt;br&gt;</span>
    If you have any questions regarding the legality or possible restrictions of a shot please don’t hesitate to ask.  <span style="color: rgb(231, 95, 85)">&lt;/p&gt;</span>
<span style="color: rgb(231, 95, 85)">&lt;/div&gt;</span>
<span style="color: rgb(231, 95, 85)">&lt;div</span> <span style="color: #a6e22e">id=</span><span style="color: #e6db74">&quot;caaLogo&quot;</span><span style="color: rgb(231, 95, 85)">&gt;&lt;/div&gt;</span>
    

<span style="color: rgb(231, 95, 85)">&lt;/section&gt;</span>


<span style="color: #75715e">&lt;?php</span> <span style="color: #66d9ef">include</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;phpIncludes/footer.php&quot;</span><span style="color: #f8f8f2">)</span> <span style="color: #75715e">?&gt;</span>
</pre></div>
</code>