<code id="clientsCode"><!-- HTML generated using hilite.me --><div style="background: #272822; overflow:auto;width:auto;border:none;border-width:.1em .1em .1em .8em;padding:.2em .6em;"><pre style="margin: 0; line-height: 125%"><span style="color: #75715e">&lt;?php</span> <span style="color: #66d9ef">include</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;phpIncludes/header_nav.php&quot;</span><span style="color: #f8f8f2">)</span> <span style="color: #75715e">?&gt;</span>


<span style="color: rgb(231, 95, 85)">&lt;section</span> <span style="color: #a6e22e">id=</span><span style="color: #e6db74">&quot;cinecoptersClients&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>

<span style="color: rgb(231, 95, 85)">&lt;div</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;imgContainer&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
      <span style="color: rgb(231, 95, 85)">&lt;div</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">bgImg</span><span style="color: rgb(231, 95, 85)">&gt;</span>
        <span style="color: rgb(231, 95, 85)">&lt;div</span> <span style="color: #a6e22e">id=</span><span style="color: #e6db74">&quot;title&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
          <span style="color: rgb(231, 95, 85)">&lt;h2&gt;</span>Our Clients<span style="color: rgb(231, 95, 85)">&lt;/h2&gt;</span>
        <span style="color: rgb(231, 95, 85)">&lt;/div&gt;</span>
          <span style="color: rgb(231, 95, 85)">&lt;div</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;aboutText&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;p&gt;</span>Just a small display of the films, TV dramas, TV series, commercials<span style="color: rgb(231, 95, 85)">&lt;br&gt;</span> and documentaries that entrusted CineCopters with their aerial footage. <span style="color: rgb(231, 95, 85)">&lt;/p&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;div</span> <span style="color: #a6e22e">id=</span><span style="color: #e6db74">&quot;clientBounceBtn&quot;</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;arrow bounce&quot;</span><span style="color: rgb(231, 95, 85)">&gt;&lt;i</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;fa fa-angle-down fa-3x&quot;</span> <span style="color: #a6e22e">aria-hidden=</span><span style="color: #e6db74">&quot;true&quot;</span><span style="color: rgb(231, 95, 85)">&gt;&lt;/i&gt;&lt;/div&gt;</span>
        <span style="color: rgb(231, 95, 85)">&lt;/div&gt;</span>
      <span style="color: rgb(231, 95, 85)">&lt;/div&gt;</span>
    <span style="color: rgb(231, 95, 85)">&lt;/div&gt;</span>

  <span style="color: rgb(231, 95, 85)">&lt;div</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;container&quot;</span> <span style="color: #a6e22e">id=</span><span style="color: #e6db74">&quot;imgGalleryWrapper&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
		<span style="color: rgb(231, 95, 85)">&lt;div</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;row&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;div</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;col-lg-3 col-md-4 col-xs-6 thumb&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;a</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;thumbnail&quot;</span> <span style="color: #a6e22e">href=</span><span style="color: #e6db74">&quot;#&quot;</span> <span style="color: #a6e22e">data-image-id=</span><span style="color: #e6db74">&quot;&quot;</span> <span style="color: #a6e22e">data-toggle=</span><span style="color: #e6db74">&quot;modal&quot;</span> <span style="color: #a6e22e">data-title=</span><span style="color: #e6db74">&quot;CineCopters - Four Kids and IT | Feature Film&quot;</span>
                   <span style="color: #a6e22e">data-image=</span><span style="color: #e6db74">&quot;/img/posters/4 Kids.jpg&quot;</span>
                   <span style="color: #a6e22e">data-target=</span><span style="color: #e6db74">&quot;#image-gallery&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                    <span style="color: rgb(231, 95, 85)">&lt;img</span> <span style="color: #a6e22e">id=</span><span style="color: #e6db74">&quot;test&quot;</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;img-thumbnail&quot;</span><span style="color: #a6e22e">src=</span><span style="color: #e6db74">&quot;/img/posters/4 Kids.jpg&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;/a&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;/div&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;div</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;col-lg-3 col-md-4 col-xs-6 thumb&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;a</span> <span style="color: #a6e22e">id=</span><span style="color: #e6db74">&quot;&quot;</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;thumbnail&quot;</span> <span style="color: #a6e22e">href=</span><span style="color: #e6db74">&quot;#&quot;</span> <span style="color: #a6e22e">data-image-id=</span><span style="color: #e6db74">&quot;&quot;</span> <span style="color: #a6e22e">data-toggle=</span><span style="color: #e6db74">&quot;modal&quot;</span> <span style="color: #a6e22e">data-title=</span><span style="color: #e6db74">&quot;CineCopters - Stephen Spielberg&#39;s | &#39;The Turning&#39; &quot;</span>
                   <span style="color: #a6e22e">data-image=</span><span style="color: #e6db74">&quot;/img/posters/The Turning.jpg&quot;</span>
                   <span style="color: #a6e22e">data-target=</span><span style="color: #e6db74">&quot;#image-gallery&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                    <span style="color: rgb(231, 95, 85)">&lt;img</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;img-thumbnail&quot;</span><span style="color: #a6e22e">src=</span><span style="color: #e6db74">&quot;/img/posters/The Turning.jpg&quot;</span>
                   <span style="color: #a6e22e">data-target=</span><span style="color: #e6db74">&quot;#image-gallery&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;/a&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;/div&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;div</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;col-lg-3 col-md-4 col-xs-6 thumb&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;a</span> <span style="color: #a6e22e">id=</span><span style="color: #e6db74">&quot;&quot;</span><span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;thumbnail&quot;</span> <span style="color: #a6e22e">href=</span><span style="color: #e6db74">&quot;#&quot;</span> <span style="color: #a6e22e">data-image-id=</span><span style="color: #e6db74">&quot;&quot;</span> <span style="color: #a6e22e">data-toggle=</span><span style="color: #e6db74">&quot;modal&quot;</span> <span style="color: #a6e22e">data-title=</span><span style="color: #e6db74">&quot;CineCopters - Sea Fever | Feature Film&quot;</span>
                   <span style="color: #a6e22e">data-image=</span><span style="color: #e6db74">&quot;/img/posters/Sea Fever.jpg&quot;</span>
                   <span style="color: #a6e22e">data-target=</span><span style="color: #e6db74">&quot;#image-gallery&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                    <span style="color: rgb(231, 95, 85)">&lt;img</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;img-thumbnail&quot;</span><span style="color: #a6e22e">src=</span><span style="color: #e6db74">&quot;/img/posters/Sea Fever.jpg&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;/a&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;/div&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;div</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;col-lg-3 col-md-4 col-xs-6 thumb&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;a</span> <span style="color: #a6e22e">id=</span><span style="color: #e6db74">&quot;&quot;</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;thumbnail&quot;</span> <span style="color: #a6e22e">href=</span><span style="color: #e6db74">&quot;#&quot;</span> <span style="color: #a6e22e">data-image-id=</span><span style="color: #e6db74">&quot;&quot;</span> <span style="color: #a6e22e">data-toggle=</span><span style="color: #e6db74">&quot;modal&quot;</span> <span style="color: #a6e22e">data-title=</span><span style="color: #e6db74">&quot;CineCopters - The Other Lamb | Feature Film&quot;</span>
                   <span style="color: #a6e22e">data-image=</span><span style="color: #e6db74">&quot;/img/posters/The Other Lamb.jpg&quot;</span>
                   <span style="color: #a6e22e">data-target=</span><span style="color: #e6db74">&quot;#image-gallery&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                    <span style="color: rgb(231, 95, 85)">&lt;img</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;img-thumbnail&quot;</span><span style="color: #a6e22e">src=</span><span style="color: #e6db74">&quot;/img/posters/The Other Lamb.jpg&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;/a&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;/div&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;div</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;col-lg-3 col-md-4 col-xs-6 thumb&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;a</span> <span style="color: #a6e22e">id=</span><span style="color: #e6db74">&quot;&quot;</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;thumbnail&quot;</span> <span style="color: #a6e22e">href=</span><span style="color: #e6db74">&quot;#&quot;</span> <span style="color: #a6e22e">data-image-id=</span><span style="color: #e6db74">&quot;&quot;</span> <span style="color: #a6e22e">data-toggle=</span><span style="color: #e6db74">&quot;modal&quot;</span> <span style="color: #a6e22e">data-title=</span><span style="color: #e6db74">&quot;CineCopters - Derry Girls 1 &amp; 2&quot;</span>
                   <span style="color: #a6e22e">data-image=</span><span style="color: #e6db74">&quot;/img/posters2/derry girls.jpg&quot;</span>
                   <span style="color: #a6e22e">data-target=</span><span style="color: #e6db74">&quot;#image-gallery&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                    <span style="color: rgb(231, 95, 85)">&lt;img</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;img-thumbnail&quot;</span><span style="color: #a6e22e">src=</span><span style="color: #e6db74">&quot;/img/posters2/derry girls.jpg&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;/a&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;/div&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;div</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;col-lg-3 col-md-4 col-xs-6 thumb&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;a</span> <span style="color: #a6e22e">id=</span><span style="color: #e6db74">&quot;&quot;</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;thumbnail&quot;</span> <span style="color: #a6e22e">href=</span><span style="color: #e6db74">&quot;#&quot;</span> <span style="color: #a6e22e">data-image-id=</span><span style="color: #e6db74">&quot;&quot;</span> <span style="color: #a6e22e">data-toggle=</span><span style="color: #e6db74">&quot;modal&quot;</span> <span style="color: #a6e22e">data-title=</span><span style="color: #e6db74">&quot;CineCopters - Extra Ordinary | Feature Film&quot;</span>
                   <span style="color: #a6e22e">data-image=</span><span style="color: #e6db74">&quot;/img/posters2/extra ordinary.jpg&quot;</span>
                   <span style="color: #a6e22e">data-target=</span><span style="color: #e6db74">&quot;#image-gallery&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                    <span style="color: rgb(231, 95, 85)">&lt;img</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;img-thumbnail&quot;</span><span style="color: #a6e22e">src=</span><span style="color: #e6db74">&quot;/img/posters2/extra ordinary.jpg&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;/a&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;/div&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;div</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;col-lg-3 col-md-4 col-xs-6 thumb&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;a</span> <span style="color: #a6e22e">id=</span><span style="color: #e6db74">&quot;&quot;</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;thumbnail&quot;</span> <span style="color: #a6e22e">href=</span><span style="color: #e6db74">&quot;#&quot;</span> <span style="color: #a6e22e">data-image-id=</span><span style="color: #e6db74">&quot;&quot;</span> <span style="color: #a6e22e">data-toggle=</span><span style="color: #e6db74">&quot;modal&quot;</span> <span style="color: #a6e22e">data-title=</span><span style="color: #e6db74">&quot;CineCopters - Into The Badlands 3&quot;</span>
                   <span style="color: #a6e22e">data-image=</span><span style="color: #e6db74">&quot;/img/posters2/badlands.jpg&quot;</span>
                   <span style="color: #a6e22e">data-target=</span><span style="color: #e6db74">&quot;#image-gallery&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                    <span style="color: rgb(231, 95, 85)">&lt;img</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;img-thumbnail&quot;</span><span style="color: #a6e22e">src=</span><span style="color: #e6db74">&quot;/img/posters2/badlands.jpg&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;/a&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;/div&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;div</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;col-lg-3 col-md-4 col-xs-6 thumb&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;a</span> <span style="color: #a6e22e">id=</span><span style="color: #e6db74">&quot;&quot;</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;thumbnail&quot;</span> <span style="color: #a6e22e">href=</span><span style="color: #e6db74">&quot;#&quot;</span> <span style="color: #a6e22e">data-image-id=</span><span style="color: #e6db74">&quot;&quot;</span> <span style="color: #a6e22e">data-toggle=</span><span style="color: #e6db74">&quot;modal&quot;</span> <span style="color: #a6e22e">data-title=</span><span style="color: #e6db74">&quot;CineCopters - Blood | TV Drama&quot;</span>
                   <span style="color: #a6e22e">data-image=</span><span style="color: #e6db74">&quot;/img/posters2/blood.jpg&quot;</span>
                   <span style="color: #a6e22e">data-target=</span><span style="color: #e6db74">&quot;#image-gallery&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                    <span style="color: rgb(231, 95, 85)">&lt;img</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;img-thumbnail&quot;</span><span style="color: #a6e22e">src=</span><span style="color: #e6db74">&quot;/img/posters2/blood.jpg&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;/a&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;/div&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;div</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;col-lg-3 col-md-4 col-xs-6 thumb&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;a</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;thumbnail&quot;</span> <span style="color: #a6e22e">href=</span><span style="color: #e6db74">&quot;#&quot;</span> <span style="color: #a6e22e">data-image-id=</span><span style="color: #e6db74">&quot;&quot;</span> <span style="color: #a6e22e">data-toggle=</span><span style="color: #e6db74">&quot;modal&quot;</span> <span style="color: #a6e22e">data-title=</span><span style="color: #e6db74">&quot;CineCopters - Line Of Duty 6&quot;</span>
                   <span style="color: #a6e22e">data-image=</span><span style="color: #e6db74">&quot;/img/posters2/LOD6.jpg&quot;</span>
                   <span style="color: #a6e22e">data-target=</span><span style="color: #e6db74">&quot;#image-gallery&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                    <span style="color: rgb(231, 95, 85)">&lt;img</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;img-thumbnail&quot;</span><span style="color: #a6e22e">src=</span><span style="color: #e6db74">&quot;/img/posters2/LOD6.jpg&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;/a&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;/div&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;div</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;col-lg-3 col-md-4 col-xs-6 thumb&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;a</span> <span style="color: #a6e22e">id=</span><span style="color: #e6db74">&quot;&quot;</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;thumbnail&quot;</span> <span style="color: #a6e22e">href=</span><span style="color: #e6db74">&quot;#&quot;</span> <span style="color: #a6e22e">data-image-id=</span><span style="color: #e6db74">&quot;&quot;</span> <span style="color: #a6e22e">data-toggle=</span><span style="color: #e6db74">&quot;modal&quot;</span> <span style="color: #a6e22e">data-title=</span><span style="color: #e6db74">&quot;CineCopters - The Race | Feature Film&quot;</span>
                   <span style="color: #a6e22e">data-image=</span><span style="color: #e6db74">&quot;/img/posters/theracer.jpg&quot;</span>
                   <span style="color: #a6e22e">data-target=</span><span style="color: #e6db74">&quot;#image-gallery&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                    <span style="color: rgb(231, 95, 85)">&lt;img</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;img-thumbnail&quot;</span><span style="color: #a6e22e">src=</span><span style="color: #e6db74">&quot;/img/posters/theracer.jpg&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;/a&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;/div&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;div</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;col-lg-3 col-md-4 col-xs-6 thumb&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;a</span> <span style="color: #a6e22e">id=</span><span style="color: #e6db74">&quot;&quot;</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;thumbnail&quot;</span> <span style="color: #a6e22e">href=</span><span style="color: #e6db74">&quot;#&quot;</span> <span style="color: #a6e22e">data-image-id=</span><span style="color: #e6db74">&quot;&quot;</span> <span style="color: #a6e22e">data-toggle=</span><span style="color: #e6db74">&quot;modal&quot;</span> <span style="color: #a6e22e">data-title=</span><span style="color: #e6db74">&quot;CineCopters - Danny Boyle &#39;Pages of the Sea&#39;&quot;</span>
                   <span style="color: #a6e22e">data-image=</span><span style="color: #e6db74">&quot;/img/posters2/Pages of the Sea.jpg&quot;</span>
                   <span style="color: #a6e22e">data-target=</span><span style="color: #e6db74">&quot;#image-gallery&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                    <span style="color: rgb(231, 95, 85)">&lt;img</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;img-thumbnail&quot;</span><span style="color: #a6e22e">src=</span><span style="color: #e6db74">&quot;/img/posters2/Pages of the Sea.jpg&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;/a&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;/div&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;div</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;col-lg-3 col-md-4 col-xs-6 thumb&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;a</span> <span style="color: #a6e22e">id=</span><span style="color: #e6db74">&quot;&quot;</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;thumbnail&quot;</span> <span style="color: #a6e22e">href=</span><span style="color: #e6db74">&quot;#&quot;</span> <span style="color: #a6e22e">data-image-id=</span><span style="color: #e6db74">&quot;&quot;</span> <span style="color: #a6e22e">data-toggle=</span><span style="color: #e6db74">&quot;modal&quot;</span> <span style="color: #a6e22e">data-title=</span><span style="color: #e6db74">&quot;CineCopters - Guinness Commercial&quot;</span>
                   <span style="color: #a6e22e">data-image=</span><span style="color: #e6db74">&quot;/img/posters/guinness.jpg&quot;</span>
                   <span style="color: #a6e22e">data-target=</span><span style="color: #e6db74">&quot;#image-gallery&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                    <span style="color: rgb(231, 95, 85)">&lt;img</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;img-thumbnail&quot;</span><span style="color: #a6e22e">src=</span><span style="color: #e6db74">&quot;/img/posters/guinness.jpg&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;/a&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;/div&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;div</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;col-lg-3 col-md-4 col-xs-6 thumb&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;a</span> <span style="color: #a6e22e">id=</span><span style="color: #e6db74">&quot;&quot;</span> <span style="color: #a6e22e">id=</span><span style="color: #e6db74">&quot;samlukeImg&quot;</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;thumbnail&quot;</span> <span style="color: #a6e22e">href=</span><span style="color: #e6db74">&quot;#&quot;</span> <span style="color: #a6e22e">data-image-id=</span><span style="color: #e6db74">&quot;&quot;</span> <span style="color: #a6e22e">data-toggle=</span><span style="color: #e6db74">&quot;modal&quot;</span> <span style="color: #a6e22e">data-title=</span><span style="color: #e6db74">&quot;CineCopters - Ford ST Commercial&quot;</span>
                   <span style="color: #a6e22e">data-image=</span><span style="color: #e6db74">&quot;/img/posters/Ford ST 2.jpg&quot;</span>
                   <span style="color: #a6e22e">data-target=</span><span style="color: #e6db74">&quot;#image-gallery&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                    <span style="color: rgb(231, 95, 85)">&lt;img</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;img-thumbnail&quot;</span><span style="color: #a6e22e">src=</span><span style="color: #e6db74">&quot;/img/posters/Ford ST 2.jpg&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;/a&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;/div&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;div</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;col-lg-3 col-md-4 col-xs-6 thumb&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;a</span> <span style="color: #a6e22e">id=</span><span style="color: #e6db74">&quot;&quot;</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;thumbnail&quot;</span> <span style="color: #a6e22e">href=</span><span style="color: #e6db74">&quot;#&quot;</span> <span style="color: #a6e22e">data-image-id=</span><span style="color: #e6db74">&quot;&quot;</span> <span style="color: #a6e22e">data-toggle=</span><span style="color: #e6db74">&quot;modal&quot;</span> <span style="color: #a6e22e">data-title=</span><span style="color: #e6db74">&quot;CineCopters - Nissan GTR Commercial&quot;</span>
                   <span style="color: #a6e22e">data-image=</span><span style="color: #e6db74">&quot;/img/posters/GTR.jpg&quot;</span>
                   <span style="color: #a6e22e">data-target=</span><span style="color: #e6db74">&quot;#image-gallery&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                    <span style="color: rgb(231, 95, 85)">&lt;img</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;img-thumbnail&quot;</span><span style="color: #a6e22e">src=</span><span style="color: #e6db74">&quot;/img/posters/GTR.jpg&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;/a&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;/div&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;div</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;col-lg-3 col-md-4 col-xs-6 thumb&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;a</span> <span style="color: #a6e22e">id=</span><span style="color: #e6db74">&quot;&quot;</span> <span style="color: #a6e22e">id=</span><span style="color: #e6db74">&quot;samlukeImg&quot;</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;thumbnail&quot;</span> <span style="color: #a6e22e">href=</span><span style="color: #e6db74">&quot;#&quot;</span> <span style="color: #a6e22e">data-image-id=</span><span style="color: #e6db74">&quot;&quot;</span> <span style="color: #a6e22e">data-toggle=</span><span style="color: #e6db74">&quot;modal&quot;</span> <span style="color: #a6e22e">data-title=</span><span style="color: #e6db74">&quot;CineCopters - Jaguar Commercial&quot;</span>
                   <span style="color: #a6e22e">data-image=</span><span style="color: #e6db74">&quot;/img/posters/jag.png&quot;</span>
                   <span style="color: #a6e22e">data-target=</span><span style="color: #e6db74">&quot;#image-gallery&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                    <span style="color: rgb(231, 95, 85)">&lt;img</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;img-thumbnail&quot;</span><span style="color: #a6e22e">src=</span><span style="color: #e6db74">&quot;/img/posters/jag.png&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;/a&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;/div&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;div</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;col-lg-3 col-md-4 col-xs-6 thumb&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;a</span> <span style="color: #a6e22e">id=</span><span style="color: #e6db74">&quot;&quot;</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;thumbnail&quot;</span> <span style="color: #a6e22e">href=</span><span style="color: #e6db74">&quot;#&quot;</span> <span style="color: #a6e22e">data-image-id=</span><span style="color: #e6db74">&quot;&quot;</span> <span style="color: #a6e22e">data-toggle=</span><span style="color: #e6db74">&quot;modal&quot;</span> <span style="color: #a6e22e">data-title=</span><span style="color: #e6db74">&quot;CineCopters - Mercedes Commercial&quot;</span>
                   <span style="color: #a6e22e">data-image=</span><span style="color: #e6db74">&quot;/img/posters/Mercedes Poster.jpg&quot;</span>
                   <span style="color: #a6e22e">data-target=</span><span style="color: #e6db74">&quot;#image-gallery&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                    <span style="color: rgb(231, 95, 85)">&lt;img</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;img-thumbnail&quot;</span><span style="color: #a6e22e">src=</span><span style="color: #e6db74">&quot;/img/posters/Mercedes Poster.jpg&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;/a&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;/div&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;div</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;col-lg-3 col-md-4 col-xs-6 thumb&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;a</span> <span style="color: #a6e22e">id=</span><span style="color: #e6db74">&quot;&quot;</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;thumbnail&quot;</span> <span style="color: #a6e22e">href=</span><span style="color: #e6db74">&quot;#&quot;</span> <span style="color: #a6e22e">data-image-id=</span><span style="color: #e6db74">&quot;&quot;</span> <span style="color: #a6e22e">data-toggle=</span><span style="color: #e6db74">&quot;modal&quot;</span> <span style="color: #a6e22e">data-title=</span><span style="color: #e6db74">&quot;CineCopters - Land Rover Commercial&quot;</span>
                   <span style="color: #a6e22e">data-image=</span><span style="color: #e6db74">&quot;/img/posters/landroverdisco.jpg&quot;</span>
                   <span style="color: #a6e22e">data-target=</span><span style="color: #e6db74">&quot;#image-gallery&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                    <span style="color: rgb(231, 95, 85)">&lt;img</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;img-thumbnail&quot;</span><span style="color: #a6e22e">src=</span><span style="color: #e6db74">&quot;/img/posters/landroverdisco.jpg&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;/a&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;/div&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;div</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;col-lg-3 col-md-4 col-xs-6 thumb&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;a</span> <span style="color: #a6e22e">id=</span><span style="color: #e6db74">&quot;&quot;</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;thumbnail&quot;</span> <span style="color: #a6e22e">href=</span><span style="color: #e6db74">&quot;#&quot;</span> <span style="color: #a6e22e">data-image-id=</span><span style="color: #e6db74">&quot;&quot;</span> <span style="color: #a6e22e">data-toggle=</span><span style="color: #e6db74">&quot;modal&quot;</span> <span style="color: #a6e22e">data-title=</span><span style="color: #e6db74">&quot;CineCopters - Citreon Commercial&quot;</span>
                   <span style="color: #a6e22e">data-image=</span><span style="color: #e6db74">&quot;/img/posters/Citreon Poster.jpg&quot;</span>
                   <span style="color: #a6e22e">data-target=</span><span style="color: #e6db74">&quot;#image-gallery&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                    <span style="color: rgb(231, 95, 85)">&lt;img</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;img-thumbnail&quot;</span><span style="color: #a6e22e">src=</span><span style="color: #e6db74">&quot;/img/posters/Citreon Poster.jpg&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;/a&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;/div&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;div</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;col-lg-3 col-md-4 col-xs-6 thumb&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;a</span> <span style="color: #a6e22e">id=</span><span style="color: #e6db74">&quot;&quot;</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;thumbnail&quot;</span> <span style="color: #a6e22e">href=</span><span style="color: #e6db74">&quot;#&quot;</span> <span style="color: #a6e22e">data-image-id=</span><span style="color: #e6db74">&quot;&quot;</span> <span style="color: #a6e22e">data-toggle=</span><span style="color: #e6db74">&quot;modal&quot;</span> <span style="color: #a6e22e">data-title=</span><span style="color: #e6db74">&quot;CineCopters - Snow Patrol Live OB&quot;</span>
                   <span style="color: #a6e22e">data-image=</span><span style="color: #e6db74">&quot;/img/posters/snow patrol.jpg&quot;</span>
                   <span style="color: #a6e22e">data-target=</span><span style="color: #e6db74">&quot;#image-gallery&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                    <span style="color: rgb(231, 95, 85)">&lt;img</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;img-thumbnail&quot;</span><span style="color: #a6e22e">src=</span><span style="color: #e6db74">&quot;/img/posters/snow patrol.jpg&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;/a&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;/div&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;div</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;col-lg-3 col-md-4 col-xs-6 thumb&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;a</span> <span style="color: #a6e22e">id=</span><span style="color: #e6db74">&quot;&quot;</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;thumbnail&quot;</span> <span style="color: #a6e22e">href=</span><span style="color: #e6db74">&quot;#&quot;</span> <span style="color: #a6e22e">data-image-id=</span><span style="color: #e6db74">&quot;&quot;</span> <span style="color: #a6e22e">data-toggle=</span><span style="color: #e6db74">&quot;modal&quot;</span> <span style="color: #a6e22e">data-title=</span><span style="color: #e6db74">&quot;CineCopters - Pixie | Feature Film&quot;</span>
                   <span style="color: #a6e22e">data-image=</span><span style="color: #e6db74">&quot;/img/pixie.jpg&quot;</span>
                   <span style="color: #a6e22e">data-target=</span><span style="color: #e6db74">&quot;#image-gallery&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                    <span style="color: rgb(231, 95, 85)">&lt;img</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;img-thumbnail&quot;</span><span style="color: #a6e22e">src=</span><span style="color: #e6db74">&quot;/img/pixie.jpg&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;/a&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;/div&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;div</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;col-lg-3 col-md-4 col-xs-6 thumb&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;a</span> <span style="color: #a6e22e">id=</span><span style="color: #e6db74">&quot;&quot;</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;thumbnail&quot;</span> <span style="color: #a6e22e">href=</span><span style="color: #e6db74">&quot;#&quot;</span> <span style="color: #a6e22e">data-image-id=</span><span style="color: #e6db74">&quot;&quot;</span> <span style="color: #a6e22e">data-toggle=</span><span style="color: #e6db74">&quot;modal&quot;</span> <span style="color: #a6e22e">data-title=</span><span style="color: #e6db74">&quot;CineCopters - Wave Goodbye to Dinosaurs | Feature Doc&quot;</span>
                   <span style="color: #a6e22e">data-image=</span><span style="color: #e6db74">&quot;/img/posters/dinos.jpg&quot;</span>
                   <span style="color: #a6e22e">data-target=</span><span style="color: #e6db74">&quot;#image-gallery&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                    <span style="color: rgb(231, 95, 85)">&lt;img</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;img-thumbnail&quot;</span><span style="color: #a6e22e">src=</span><span style="color: #e6db74">&quot;/img/posters/dinos.jpg&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;/a&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;/div&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;div</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;col-lg-3 col-md-4 col-xs-6 thumb&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;a</span> <span style="color: #a6e22e">id=</span><span style="color: #e6db74">&quot;&quot;</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;thumbnail&quot;</span> <span style="color: #a6e22e">href=</span><span style="color: #e6db74">&quot;#&quot;</span> <span style="color: #a6e22e">data-image-id=</span><span style="color: #e6db74">&quot;&quot;</span> <span style="color: #a6e22e">data-toggle=</span><span style="color: #e6db74">&quot;modal&quot;</span> <span style="color: #a6e22e">data-title=</span><span style="color: #e6db74">&quot;CineCopters - Penance | TV Drama&quot;</span>
                   <span style="color: #a6e22e">data-image=</span><span style="color: #e6db74">&quot;/img/posters/penance.jpg&quot;</span>
                   <span style="color: #a6e22e">data-target=</span><span style="color: #e6db74">&quot;#image-gallery&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                    <span style="color: rgb(231, 95, 85)">&lt;img</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;img-thumbnail&quot;</span><span style="color: #a6e22e">src=</span><span style="color: #e6db74">&quot;/img/posters/penance.jpg&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;/a&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;/div&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;div</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;col-lg-3 col-md-4 col-xs-6 thumb&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;a</span> <span style="color: #a6e22e">id=</span><span style="color: #e6db74">&quot;&quot;</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;thumbnail&quot;</span> <span style="color: #a6e22e">href=</span><span style="color: #e6db74">&quot;#&quot;</span> <span style="color: #a6e22e">data-image-id=</span><span style="color: #e6db74">&quot;&quot;</span> <span style="color: #a6e22e">data-toggle=</span><span style="color: #e6db74">&quot;modal&quot;</span> <span style="color: #a6e22e">data-title=</span><span style="color: #e6db74">&quot;CineCopters - Discovery&quot;</span>
                   <span style="color: #a6e22e">data-image=</span><span style="color: #e6db74">&quot;/img/posters/Discovery.jpg&quot;</span>
                   <span style="color: #a6e22e">data-target=</span><span style="color: #e6db74">&quot;#image-gallery&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                    <span style="color: rgb(231, 95, 85)">&lt;img</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;img-thumbnail&quot;</span><span style="color: #a6e22e">src=</span><span style="color: #e6db74">&quot;/img/posters/Discovery.jpg&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;/a&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;/div&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;div</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;col-lg-3 col-md-4 col-xs-6 thumb&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;a</span> <span style="color: #a6e22e">id=</span><span style="color: #e6db74">&quot;&quot;</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;thumbnail&quot;</span> <span style="color: #a6e22e">href=</span><span style="color: #e6db74">&quot;#&quot;</span> <span style="color: #a6e22e">data-image-id=</span><span style="color: #e6db74">&quot;&quot;</span> <span style="color: #a6e22e">data-toggle=</span><span style="color: #e6db74">&quot;modal&quot;</span> <span style="color: #a6e22e">data-title=</span><span style="color: #e6db74">&quot;CineCopters - Secret Britian&quot;</span>
                   <span style="color: #a6e22e">data-image=</span><span style="color: #e6db74">&quot;/img/posters2/Secret Britain.jpg&quot;</span>
                   <span style="color: #a6e22e">data-target=</span><span style="color: #e6db74">&quot;#image-gallery&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                    <span style="color: rgb(231, 95, 85)">&lt;img</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;img-thumbnail&quot;</span><span style="color: #a6e22e">src=</span><span style="color: #e6db74">&quot;/img/posters2/Secret Britain.jpg&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;/a&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;/div&gt;</span>
            


        <span style="color: rgb(231, 95, 85)">&lt;div</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;modal fade&quot;</span> <span style="color: #a6e22e">id=</span><span style="color: #e6db74">&quot;image-gallery&quot;</span> <span style="color: #a6e22e">tabindex=</span><span style="color: #e6db74">&quot;-1&quot;</span> <span style="color: #a6e22e">role=</span><span style="color: #e6db74">&quot;dialog&quot;</span> <span style="color: #a6e22e">aria-labelledby=</span><span style="color: #e6db74">&quot;myModalLabel&quot;</span> <span style="color: #a6e22e">aria-hidden=</span><span style="color: #e6db74">&quot;true&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;div</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;modal-dialog modal-lg&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;div</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;modal-content&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                    <span style="color: rgb(231, 95, 85)">&lt;div</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;modal-header&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                        <span style="color: rgb(231, 95, 85)">&lt;h4</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;modal-title&quot;</span> <span style="color: #a6e22e">id=</span><span style="color: #e6db74">&quot;image-gallery-title&quot;</span><span style="color: rgb(231, 95, 85)">&gt;&lt;/h4&gt;</span>
                        <span style="color: rgb(231, 95, 85)">&lt;button</span> <span style="color: #a6e22e">type=</span><span style="color: #e6db74">&quot;button&quot;</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;close&quot;</span> <span style="color: #a6e22e">data-dismiss=</span><span style="color: #e6db74">&quot;modal&quot;</span><span style="color: rgb(231, 95, 85)">&gt;&lt;span</span> <span style="color: #a6e22e">aria-hidden=</span><span style="color: #e6db74">&quot;true&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>×<span style="color: rgb(231, 95, 85)">&lt;/span&gt;&lt;span</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;sr-only&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>Close<span style="color: rgb(231, 95, 85)">&lt;/span&gt;</span>
                        <span style="color: rgb(231, 95, 85)">&lt;/button&gt;</span>
                    <span style="color: rgb(231, 95, 85)">&lt;/div&gt;</span>
                    <span style="color: rgb(231, 95, 85)">&lt;div</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;modal-body&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                        <span style="color: rgb(231, 95, 85)">&lt;img</span> <span style="color: #a6e22e">id=</span><span style="color: #e6db74">&quot;image-gallery-image&quot;</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;img-responsive col-md-12&quot;</span> <span style="color: #a6e22e">src=</span><span style="color: #e6db74">&quot;&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                    <span style="color: rgb(231, 95, 85)">&lt;/div&gt;</span>
                    <span style="color: rgb(231, 95, 85)">&lt;div</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;modal-footer&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
                        <span style="color: rgb(231, 95, 85)">&lt;button</span> <span style="color: #a6e22e">type=</span><span style="color: #e6db74">&quot;button&quot;</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;btn btn-secondary float-left&quot;</span> <span style="color: #a6e22e">id=</span><span style="color: #e6db74">&quot;show-previous-image&quot;</span><span style="color: rgb(231, 95, 85)">&gt;&lt;i</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;fa fa-arrow-left&quot;</span><span style="color: rgb(231, 95, 85)">&gt;&lt;/i&gt;</span>
                        <span style="color: rgb(231, 95, 85)">&lt;/button&gt;</span>

                        <span style="color: rgb(231, 95, 85)">&lt;button</span> <span style="color: #a6e22e">type=</span><span style="color: #e6db74">&quot;button&quot;</span> <span style="color: #a6e22e">id=</span><span style="color: #e6db74">&quot;show-next-image&quot;</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;btn btn-secondary float-right&quot;</span><span style="color: rgb(231, 95, 85)">&gt;&lt;i</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;fa fa-arrow-right&quot;</span><span style="color: rgb(231, 95, 85)">&gt;&lt;/i&gt;</span>
                        <span style="color: rgb(231, 95, 85)">&lt;/button&gt;</span>
                    <span style="color: rgb(231, 95, 85)">&lt;/div&gt;</span>
                <span style="color: rgb(231, 95, 85)">&lt;/div&gt;</span>
            <span style="color: rgb(231, 95, 85)">&lt;/div&gt;</span>
        <span style="color: rgb(231, 95, 85)">&lt;/div&gt;</span>
<span style="color: rgb(231, 95, 85)">&lt;/div&gt;</span>



  <span style="color: #75715e">&lt;!--Back to Top Button--&gt;</span>
  <span style="color: rgb(231, 95, 85)">&lt;button</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;btn&quot;</span> <span style="color: #a6e22e">id=</span><span style="color: #e6db74">&quot;backToTop&quot;</span> <span style="color: #a6e22e">onclick=</span><span style="color: #e6db74">&quot;topFunction()&quot;</span> <span style="color: #a6e22e">title=</span><span style="color: #e6db74">&quot;Go to top&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>	<span style="color: #f8f8f2">&amp;#8593;</span><span style="color: rgb(231, 95, 85)">&lt;/button&gt;</span>

<span style="color: rgb(231, 95, 85)">&lt;/section&gt;</span>


<span style="color: #75715e">&lt;?php</span> <span style="color: #66d9ef">include</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;phpIncludes/footer.php&quot;</span><span style="color: #f8f8f2">)</span> <span style="color: #75715e">?&gt;</span>
</pre></div>
</code>