<!-- HTML generated using hilite.me --><div style="background: #272822; overflow:auto;width:auto;border:none;border-width:.1em .1em .1em .8em;padding:.2em .6em;"><pre style="margin: 0; line-height: 125%"><span style="color: #75715e">//ABOUT PAGE IMG GALLERY//</span>
<span style="color: #66d9ef">let</span> <span style="color: #a6e22e">modalId</span> <span style="color: rgb(231, 95, 85)">=</span> <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&#39;#image-gallery&#39;</span><span style="color: #f8f8f2">);</span>


<span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(document)</span>
  <span style="color: #f8f8f2">.</span><span style="color: #a6e22e">ready</span><span style="color: #f8f8f2">(</span><span style="color: #66d9ef">function</span> <span style="color: #f8f8f2">()</span> <span style="color: #f8f8f2">{</span>

    <span style="color: #a6e22e">loadGallery</span><span style="color: #f8f8f2">(</span><span style="color: #66d9ef">true</span><span style="color: #f8f8f2">,</span> <span style="color: #e6db74">&#39;a.thumbnail&#39;</span><span style="color: #f8f8f2">);</span>

    <span style="color: #75715e">//This function disables buttons when you&#39;re at either end of the gallery</span>
    <span style="color: #66d9ef">function</span> <span style="color: #a6e22e">disableButtons</span><span style="color: #f8f8f2">(</span><span style="color: #a6e22e">counter_max</span><span style="color: #f8f8f2">,</span> <span style="color: #a6e22e">counter_current</span><span style="color: #f8f8f2">)</span> <span style="color: #f8f8f2">{</span>
      <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&#39;#show-previous-image, #show-next-image&#39;</span><span style="color: #f8f8f2">)</span>
        <span style="color: #f8f8f2">.</span><span style="color: #a6e22e">show</span><span style="color: #f8f8f2">();</span>
      <span style="color: #66d9ef">if</span> <span style="color: #f8f8f2">(</span><span style="color: #a6e22e">counter_max</span> <span style="color: rgb(231, 95, 85)">===</span> <span style="color: #a6e22e">counter_current</span><span style="color: #f8f8f2">)</span> <span style="color: #f8f8f2">{</span>
        <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&#39;#show-next-image&#39;</span><span style="color: #f8f8f2">)</span>
          <span style="color: #f8f8f2">.</span><span style="color: #a6e22e">hide</span><span style="color: #f8f8f2">();</span>
      <span style="color: #f8f8f2">}</span> <span style="color: #66d9ef">else</span> <span style="color: #66d9ef">if</span> <span style="color: #f8f8f2">(</span><span style="color: #a6e22e">counter_current</span> <span style="color: rgb(231, 95, 85)">===</span> <span style="color: #ae81ff">1</span><span style="color: #f8f8f2">)</span> <span style="color: #f8f8f2">{</span>
        <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&#39;#show-previous-image&#39;</span><span style="color: #f8f8f2">)</span>
          <span style="color: #f8f8f2">.</span><span style="color: #a6e22e">hide</span><span style="color: #f8f8f2">();</span>
      <span style="color: #f8f8f2">}</span>
    <span style="color: #f8f8f2">}</span>

    <span style="color: #66d9ef">function</span> <span style="color: #a6e22e">loadGallery</span><span style="color: #f8f8f2">(</span><span style="color: #a6e22e">setIDs</span><span style="color: #f8f8f2">,</span> <span style="color: #a6e22e">setClickAttr</span><span style="color: #f8f8f2">)</span> <span style="color: #f8f8f2">{</span>
      <span style="color: #66d9ef">let</span> <span style="color: #a6e22e">current_image</span><span style="color: #f8f8f2">,</span>
        <span style="color: #a6e22e">selector</span><span style="color: #f8f8f2">,</span>
        <span style="color: #a6e22e">counter</span> <span style="color: rgb(231, 95, 85)">=</span> <span style="color: #ae81ff">0</span><span style="color: #f8f8f2">;</span>

      <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&#39;#show-next-image, #show-previous-image&#39;</span><span style="color: #f8f8f2">)</span>
        <span style="color: #f8f8f2">.</span><span style="color: #a6e22e">click</span><span style="color: #f8f8f2">(</span><span style="color: #66d9ef">function</span> <span style="color: #f8f8f2">()</span> <span style="color: #f8f8f2">{</span>
          <span style="color: #66d9ef">if</span> <span style="color: #f8f8f2">(</span><span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #66d9ef">this</span><span style="color: #f8f8f2">)</span>
            <span style="color: #f8f8f2">.</span><span style="color: #a6e22e">attr</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&#39;id&#39;</span><span style="color: #f8f8f2">)</span> <span style="color: rgb(231, 95, 85)">===</span> <span style="color: #e6db74">&#39;show-previous-image&#39;</span><span style="color: #f8f8f2">)</span> <span style="color: #f8f8f2">{</span>
            <span style="color: #a6e22e">current_image</span><span style="color: rgb(231, 95, 85)">--</span><span style="color: #f8f8f2">;</span>
          <span style="color: #f8f8f2">}</span> <span style="color: #66d9ef">else</span> <span style="color: #f8f8f2">{</span>
            <span style="color: #a6e22e">current_image</span><span style="color: rgb(231, 95, 85)">++</span><span style="color: #f8f8f2">;</span>
          <span style="color: #f8f8f2">}</span>

          <span style="color: #a6e22e">selector</span> <span style="color: rgb(231, 95, 85)">=</span> <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&#39;[data-image-id=&quot;&#39;</span> <span style="color: rgb(231, 95, 85)">+</span> <span style="color: #a6e22e">current_image</span> <span style="color: rgb(231, 95, 85)">+</span> <span style="color: #e6db74">&#39;&quot;]&#39;</span><span style="color: #f8f8f2">);</span>
          <span style="color: #a6e22e">updateGallery</span><span style="color: #f8f8f2">(</span><span style="color: #a6e22e">selector</span><span style="color: #f8f8f2">);</span>
        <span style="color: #f8f8f2">});</span>

      <span style="color: #66d9ef">function</span> <span style="color: #a6e22e">updateGallery</span><span style="color: #f8f8f2">(</span><span style="color: #a6e22e">selector</span><span style="color: #f8f8f2">)</span> <span style="color: #f8f8f2">{</span>
        <span style="color: #66d9ef">let</span> <span style="color: #a6e22e">$sel</span> <span style="color: rgb(231, 95, 85)">=</span> <span style="color: #a6e22e">selector</span><span style="color: #f8f8f2">;</span>
        <span style="color: #a6e22e">current_image</span> <span style="color: rgb(231, 95, 85)">=</span> <span style="color: #a6e22e">$sel</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">data</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&#39;image-id&#39;</span><span style="color: #f8f8f2">);</span>
        <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&#39;#image-gallery-title&#39;</span><span style="color: #f8f8f2">)</span>
          <span style="color: #f8f8f2">.</span><span style="color: #a6e22e">text</span><span style="color: #f8f8f2">(</span><span style="color: #a6e22e">$sel</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">data</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&#39;title&#39;</span><span style="color: #f8f8f2">));</span>
        <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&#39;#image-gallery-image&#39;</span><span style="color: #f8f8f2">)</span>
          <span style="color: #f8f8f2">.</span><span style="color: #a6e22e">attr</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&#39;src&#39;</span><span style="color: #f8f8f2">,</span> <span style="color: #a6e22e">$sel</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">data</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&#39;image&#39;</span><span style="color: #f8f8f2">));</span>
        <span style="color: #a6e22e">disableButtons</span><span style="color: #f8f8f2">(</span><span style="color: #a6e22e">counter</span><span style="color: #f8f8f2">,</span> <span style="color: #a6e22e">$sel</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">data</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&#39;image-id&#39;</span><span style="color: #f8f8f2">));</span>
      <span style="color: #f8f8f2">}</span>

      <span style="color: #66d9ef">if</span> <span style="color: #f8f8f2">(</span><span style="color: #a6e22e">setIDs</span> <span style="color: rgb(231, 95, 85)">==</span> <span style="color: #66d9ef">true</span><span style="color: #f8f8f2">)</span> <span style="color: #f8f8f2">{</span>
        <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&#39;[data-image-id]&#39;</span><span style="color: #f8f8f2">)</span>
          <span style="color: #f8f8f2">.</span><span style="color: #a6e22e">each</span><span style="color: #f8f8f2">(</span><span style="color: #66d9ef">function</span> <span style="color: #f8f8f2">()</span> <span style="color: #f8f8f2">{</span>
            <span style="color: #a6e22e">counter</span><span style="color: rgb(231, 95, 85)">++</span><span style="color: #f8f8f2">;</span>
            <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #66d9ef">this</span><span style="color: #f8f8f2">)</span>
              <span style="color: #f8f8f2">.</span><span style="color: #a6e22e">attr</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&#39;data-image-id&#39;</span><span style="color: #f8f8f2">,</span> <span style="color: #a6e22e">counter</span><span style="color: #f8f8f2">);</span>
          <span style="color: #f8f8f2">});</span>
      <span style="color: #f8f8f2">}</span>
      <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #a6e22e">setClickAttr</span><span style="color: #f8f8f2">)</span>
        <span style="color: #f8f8f2">.</span><span style="color: #a6e22e">on</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&#39;click&#39;</span><span style="color: #f8f8f2">,</span> <span style="color: #66d9ef">function</span> <span style="color: #f8f8f2">()</span> <span style="color: #f8f8f2">{</span>
          <span style="color: #a6e22e">updateGallery</span><span style="color: #f8f8f2">(</span><span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #66d9ef">this</span><span style="color: #f8f8f2">));</span>
        <span style="color: #f8f8f2">});</span>
    <span style="color: #f8f8f2">}</span>
  <span style="color: #f8f8f2">});</span>

<span style="color: #75715e">// LEFT AND RIGHT ARROW KEYS TO SCROLL THROUGH IMAGES</span>
<span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(document)</span>
  <span style="color: #f8f8f2">.</span><span style="color: #a6e22e">keydown</span><span style="color: #f8f8f2">(</span><span style="color: #66d9ef">function</span> <span style="color: #f8f8f2">(</span><span style="color: #a6e22e">e</span><span style="color: #f8f8f2">)</span> <span style="color: #f8f8f2">{</span>
    <span style="color: #66d9ef">switch</span> <span style="color: #f8f8f2">(</span><span style="color: #a6e22e">e</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">which</span><span style="color: #f8f8f2">)</span> <span style="color: #f8f8f2">{</span>
      <span style="color: #66d9ef">case</span> <span style="color: #ae81ff">37</span><span style="color: rgb(231, 95, 85)">:</span> <span style="color: #75715e">// left</span>
        <span style="color: #66d9ef">if</span> <span style="color: #f8f8f2">((</span><span style="color: #a6e22e">modalId</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">data</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&#39;bs.modal&#39;</span><span style="color: #f8f8f2">)</span> <span style="color: rgb(231, 95, 85)">||</span> <span style="color: #f8f8f2">{}).</span><span style="color: #a6e22e">_isShown</span> <span style="color: rgb(231, 95, 85)">&amp;&amp;</span> <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&#39;#show-previous-image&#39;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">is</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;:visible&quot;</span><span style="color: #f8f8f2">))</span> <span style="color: #f8f8f2">{</span>
          <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&#39;#show-previous-image&#39;</span><span style="color: #f8f8f2">)</span>
            <span style="color: #f8f8f2">.</span><span style="color: #a6e22e">click</span><span style="color: #f8f8f2">();</span>
        <span style="color: #f8f8f2">}</span>
        <span style="color: #66d9ef">break</span><span style="color: #f8f8f2">;</span>

      <span style="color: #66d9ef">case</span> <span style="color: #ae81ff">39</span><span style="color: rgb(231, 95, 85)">:</span> <span style="color: #75715e">// right</span>
        <span style="color: #66d9ef">if</span> <span style="color: #f8f8f2">((</span><span style="color: #a6e22e">modalId</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">data</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&#39;bs.modal&#39;</span><span style="color: #f8f8f2">)</span> <span style="color: rgb(231, 95, 85)">||</span> <span style="color: #f8f8f2">{}).</span><span style="color: #a6e22e">_isShown</span> <span style="color: rgb(231, 95, 85)">&amp;&amp;</span> <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&#39;#show-next-image&#39;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">is</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;:visible&quot;</span><span style="color: #f8f8f2">))</span> <span style="color: #f8f8f2">{</span>
          <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&#39;#show-next-image&#39;</span><span style="color: #f8f8f2">)</span>
            <span style="color: #f8f8f2">.</span><span style="color: #a6e22e">click</span><span style="color: #f8f8f2">();</span>
        <span style="color: #f8f8f2">}</span>
        <span style="color: #66d9ef">break</span><span style="color: #f8f8f2">;</span>

      <span style="color: #66d9ef">default</span><span style="color: rgb(231, 95, 85)">:</span>
        <span style="color: #66d9ef">return</span><span style="color: #f8f8f2">;</span> <span style="color: #75715e">// exit this handler for other keys</span>
    <span style="color: #f8f8f2">}</span>
    <span style="color: #75715e">// e.preventDefault(); // prevent the default action (scroll / move caret)</span>
  <span style="color: #f8f8f2">});</span>
<span style="color: #75715e">//END OF ABOUT PAGE IMG GALLERY</span>


<span style="color: #75715e">//EQUIPMENT PAGE IMAGE PANNELS</span>
<span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;.panel&quot;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">addClass</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;panelShadow&quot;</span><span style="color: #f8f8f2">);</span>

<span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;.panel&quot;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">mouseenter</span><span style="color: #f8f8f2">(</span><span style="color: #66d9ef">function</span> <span style="color: #f8f8f2">(</span><span style="color: #a6e22e">e</span><span style="color: #f8f8f2">){</span>
  <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #66d9ef">this</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">addClass</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;open openActive&quot;</span><span style="color: #f8f8f2">);</span>
  <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #66d9ef">this</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">removeClass</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;panelShadow&quot;</span><span style="color: #f8f8f2">);</span>
<span style="color: #f8f8f2">});</span>

<span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;.panel&quot;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">mouseleave</span><span style="color: #f8f8f2">(</span><span style="color: #66d9ef">function</span> <span style="color: #f8f8f2">(</span><span style="color: #a6e22e">e</span><span style="color: #f8f8f2">){</span>
  <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #66d9ef">this</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">removeClass</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;open openActive panelShadow&quot;</span><span style="color: #f8f8f2">);</span>
  <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #66d9ef">this</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">addClass</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;panelShadow&quot;</span><span style="color: #f8f8f2">);</span>
<span style="color: #f8f8f2">});</span>
<span style="color: #75715e">//END OF EQUIPMENT PAGE IMAGE PANNELS</span>


<span style="color: #75715e">//EQUIPMENT PAGE BACK TO TOP BUTTON</span>
<span style="color: #a6e22e">backToTop</span> <span style="color: rgb(231, 95, 85)">=</span> <span style="color: #f8f8f2">document.</span><span style="color: #a6e22e">getElementById</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;backToTop&quot;</span><span style="color: #f8f8f2">);</span>

<span style="color: #f8f8f2">window.</span><span style="color: #a6e22e">onscroll</span> <span style="color: rgb(231, 95, 85)">=</span> <span style="color: #66d9ef">function</span><span style="color: #f8f8f2">()</span> <span style="color: #f8f8f2">{</span><span style="color: #a6e22e">scrollFunction</span><span style="color: #f8f8f2">()};</span>

<span style="color: #66d9ef">function</span> <span style="color: #a6e22e">scrollFunction</span><span style="color: #f8f8f2">()</span> <span style="color: #f8f8f2">{</span>
  <span style="color: #66d9ef">if</span> <span style="color: #f8f8f2">((document.</span><span style="color: #a6e22e">documentElement</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">scrollTop</span> <span style="color: rgb(231, 95, 85)">&gt;</span> <span style="color: #ae81ff">1500</span><span style="color: #f8f8f2">)</span> <span style="color: rgb(231, 95, 85)">&amp;&amp;</span> <span style="color: #f8f8f2">(document.</span><span style="color: #a6e22e">documentElement</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">scrollTop</span> <span style="color: rgb(231, 95, 85)">&lt;</span> <span style="color: #ae81ff">8400</span><span style="color: #f8f8f2">))</span> <span style="color: #f8f8f2">{</span>
    <span style="color: #a6e22e">backToTop</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">style</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">opacity</span> <span style="color: rgb(231, 95, 85)">=</span> <span style="color: #ae81ff">1</span><span style="color: #f8f8f2">;</span>
  <span style="color: #f8f8f2">}</span>  
  <span style="color: #66d9ef">else</span> <span style="color: #f8f8f2">{</span>
    <span style="color: #a6e22e">backToTop</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">style</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">opacity</span> <span style="color: rgb(231, 95, 85)">=</span> <span style="color: #ae81ff">0</span><span style="color: #f8f8f2">;</span>
  <span style="color: #f8f8f2">}</span>
<span style="color: #f8f8f2">}</span>

<span style="color: #66d9ef">function</span> <span style="color: #a6e22e">scrollFunctionHide</span><span style="color: #f8f8f2">()</span> <span style="color: #f8f8f2">{</span>
  <span style="color: #66d9ef">if</span> <span style="color: #f8f8f2">(document.</span><span style="color: #a6e22e">body</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">scrollTop</span> <span style="color: rgb(231, 95, 85)">&gt;=</span> <span style="color: #ae81ff">9000</span> <span style="color: rgb(231, 95, 85)">||</span> <span style="color: #f8f8f2">document.</span><span style="color: #a6e22e">documentElement</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">scrollTop</span> <span style="color: rgb(231, 95, 85)">&gt;=</span> <span style="color: #ae81ff">9000</span><span style="color: #f8f8f2">)</span> <span style="color: #f8f8f2">{</span>
    <span style="color: #a6e22e">backToTop</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">style</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">display</span> <span style="color: rgb(231, 95, 85)">=</span> <span style="color: #e6db74">&quot;none&quot;</span><span style="color: #f8f8f2">;</span>
  <span style="color: #f8f8f2">}</span>
<span style="color: #f8f8f2">}</span>
<span style="color: #a6e22e">scrollFunctionHide</span><span style="color: #f8f8f2">();</span>

<span style="color: #75715e">// When the user clicks on the button, scroll to the top of the document (with offset)</span>
<span style="color: #66d9ef">function</span> <span style="color: #a6e22e">topFunction</span><span style="color: #f8f8f2">()</span> <span style="color: #f8f8f2">{</span>
  <span style="color: #f8f8f2">window.</span><span style="color: #a6e22e">scrollTo</span><span style="color: #f8f8f2">({</span><span style="color: #a6e22e">top</span><span style="color: rgb(231, 95, 85)">:</span> <span style="color: #ae81ff">700</span><span style="color: #f8f8f2">,</span> <span style="color: #a6e22e">behavior</span><span style="color: rgb(231, 95, 85)">:</span> <span style="color: #e6db74">&quot;smooth&quot;</span><span style="color: #f8f8f2">});</span>
<span style="color: #f8f8f2">}</span>
<span style="color: #75715e">//End of equipment page.</span>


<span style="color: #75715e">//Showreel Page//</span>

<span style="color: #75715e">//stop video when modal is closed **/ (fucked if I can group them at the min though!!)</span>
<span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&#39;#modal1&#39;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">on</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&#39;hidden.bs.modal&#39;</span><span style="color: #f8f8f2">,</span> <span style="color: #66d9ef">function</span> <span style="color: #f8f8f2">(</span><span style="color: #a6e22e">e</span><span style="color: #f8f8f2">)</span> <span style="color: #f8f8f2">{</span>
  <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&#39;#modal1 iframe&#39;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">attr</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;src&quot;</span><span style="color: #f8f8f2">,</span> <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;#modal1 iframe&quot;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">attr</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;src&quot;</span><span style="color: #f8f8f2">));</span>
<span style="color: #f8f8f2">});</span>
<span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&#39;#modal2&#39;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">on</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&#39;hidden.bs.modal&#39;</span><span style="color: #f8f8f2">,</span> <span style="color: #66d9ef">function</span> <span style="color: #f8f8f2">(</span><span style="color: #a6e22e">e</span><span style="color: #f8f8f2">)</span> <span style="color: #f8f8f2">{</span>
  <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&#39;#modal2 iframe&#39;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">attr</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;src&quot;</span><span style="color: #f8f8f2">,</span> <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;#modal2 iframe&quot;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">attr</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;src&quot;</span><span style="color: #f8f8f2">));</span>
<span style="color: #f8f8f2">});</span>
<span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&#39;#modal3&#39;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">on</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&#39;hidden.bs.modal&#39;</span><span style="color: #f8f8f2">,</span> <span style="color: #66d9ef">function</span> <span style="color: #f8f8f2">(</span><span style="color: #a6e22e">e</span><span style="color: #f8f8f2">)</span> <span style="color: #f8f8f2">{</span>
  <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&#39;#modal3 iframe&#39;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">attr</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;src&quot;</span><span style="color: #f8f8f2">,</span> <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;#modal3 iframe&quot;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">attr</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;src&quot;</span><span style="color: #f8f8f2">));</span>
<span style="color: #f8f8f2">});</span>
<span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&#39;#modal4&#39;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">on</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&#39;hidden.bs.modal&#39;</span><span style="color: #f8f8f2">,</span> <span style="color: #66d9ef">function</span> <span style="color: #f8f8f2">(</span><span style="color: #a6e22e">e</span><span style="color: #f8f8f2">)</span> <span style="color: #f8f8f2">{</span>
  <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&#39;#modal4 iframe&#39;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">attr</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;src&quot;</span><span style="color: #f8f8f2">,</span> <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;#modal4 iframe&quot;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">attr</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;src&quot;</span><span style="color: #f8f8f2">));</span>
<span style="color: #f8f8f2">});</span>
<span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&#39;#modal5&#39;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">on</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&#39;hidden.bs.modal&#39;</span><span style="color: #f8f8f2">,</span> <span style="color: #66d9ef">function</span> <span style="color: #f8f8f2">(</span><span style="color: #a6e22e">e</span><span style="color: #f8f8f2">)</span> <span style="color: #f8f8f2">{</span>
  <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&#39;#modal5 iframe&#39;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">attr</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;src&quot;</span><span style="color: #f8f8f2">,</span> <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;#modal5 iframe&quot;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">attr</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;src&quot;</span><span style="color: #f8f8f2">));</span>
<span style="color: #f8f8f2">});</span>
<span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&#39;#modal6&#39;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">on</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&#39;hidden.bs.modal&#39;</span><span style="color: #f8f8f2">,</span> <span style="color: #66d9ef">function</span> <span style="color: #f8f8f2">(</span><span style="color: #a6e22e">e</span><span style="color: #f8f8f2">)</span> <span style="color: #f8f8f2">{</span>
  <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&#39;#modal6 iframe&#39;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">attr</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;src&quot;</span><span style="color: #f8f8f2">,</span> <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;#modal6 iframe&quot;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">attr</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;src&quot;</span><span style="color: #f8f8f2">));</span>
<span style="color: #f8f8f2">});</span>
<span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&#39;#modal7&#39;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">on</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&#39;hidden.bs.modal&#39;</span><span style="color: #f8f8f2">,</span> <span style="color: #66d9ef">function</span> <span style="color: #f8f8f2">(</span><span style="color: #a6e22e">e</span><span style="color: #f8f8f2">)</span> <span style="color: #f8f8f2">{</span>
  <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&#39;#modal7 iframe&#39;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">attr</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;src&quot;</span><span style="color: #f8f8f2">,</span> <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;#modal7 iframe&quot;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">attr</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;src&quot;</span><span style="color: #f8f8f2">));</span>
<span style="color: #f8f8f2">});</span>
<span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&#39;#modal8&#39;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">on</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&#39;hidden.bs.modal&#39;</span><span style="color: #f8f8f2">,</span> <span style="color: #66d9ef">function</span> <span style="color: #f8f8f2">(</span><span style="color: #a6e22e">e</span><span style="color: #f8f8f2">)</span> <span style="color: #f8f8f2">{</span>
  <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&#39;#modal8 iframe&#39;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">attr</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;src&quot;</span><span style="color: #f8f8f2">,</span> <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;#modal8 iframe&quot;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">attr</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;src&quot;</span><span style="color: #f8f8f2">));</span>
<span style="color: #f8f8f2">});</span>
<span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&#39;#modal9&#39;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">on</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&#39;hidden.bs.modal&#39;</span><span style="color: #f8f8f2">,</span> <span style="color: #66d9ef">function</span> <span style="color: #f8f8f2">(</span><span style="color: #a6e22e">e</span><span style="color: #f8f8f2">)</span> <span style="color: #f8f8f2">{</span>
  <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&#39;#modal9 iframe&#39;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">attr</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;src&quot;</span><span style="color: #f8f8f2">,</span> <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;#modal9 iframe&quot;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">attr</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;src&quot;</span><span style="color: #f8f8f2">));</span>
<span style="color: #f8f8f2">});</span>
<span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&#39;#modal10&#39;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">on</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&#39;hidden.bs.modal&#39;</span><span style="color: #f8f8f2">,</span> <span style="color: #66d9ef">function</span> <span style="color: #f8f8f2">(</span><span style="color: #a6e22e">e</span><span style="color: #f8f8f2">)</span> <span style="color: #f8f8f2">{</span>
  <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&#39;#modal10 iframe&#39;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">attr</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;src&quot;</span><span style="color: #f8f8f2">,</span> <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;#modal10 iframe&quot;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">attr</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;src&quot;</span><span style="color: #f8f8f2">));</span>
<span style="color: #f8f8f2">});</span>
<span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&#39;#modal11&#39;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">on</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&#39;hidden.bs.modal&#39;</span><span style="color: #f8f8f2">,</span> <span style="color: #66d9ef">function</span> <span style="color: #f8f8f2">(</span><span style="color: #a6e22e">e</span><span style="color: #f8f8f2">)</span> <span style="color: #f8f8f2">{</span>
  <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&#39;#modal11 iframe&#39;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">attr</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;src&quot;</span><span style="color: #f8f8f2">,</span> <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;#modal11 iframe&quot;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">attr</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;src&quot;</span><span style="color: #f8f8f2">));</span>
<span style="color: #f8f8f2">});</span>
<span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&#39;#modal12&#39;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">on</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&#39;hidden.bs.modal&#39;</span><span style="color: #f8f8f2">,</span> <span style="color: #66d9ef">function</span> <span style="color: #f8f8f2">(</span><span style="color: #a6e22e">e</span><span style="color: #f8f8f2">)</span> <span style="color: #f8f8f2">{</span>
  <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&#39;#modal12 iframe&#39;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">attr</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;src&quot;</span><span style="color: #f8f8f2">,</span> <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;#modal12 iframe&quot;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">attr</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;src&quot;</span><span style="color: #f8f8f2">));</span>
<span style="color: #f8f8f2">});</span>

<span style="color: #75715e">//PLAY BUTTON ON VIDEO THUMBNAIL HOVER</span>
<span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;.fa-play&quot;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">hover</span><span style="color: #f8f8f2">(</span>
  <span style="color: #66d9ef">function</span> <span style="color: #f8f8f2">()</span> <span style="color: #f8f8f2">{</span>
    <span style="color: #75715e">// $(this).nextAll().addClass(&#39;hoverDark&#39;);</span>
    <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #66d9ef">this</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">siblings</span><span style="color: #f8f8f2">().</span><span style="color: #a6e22e">find</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;.carousel-item&quot;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">addClass</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&#39;hoverDark&#39;</span><span style="color: #f8f8f2">);</span>
  <span style="color: #f8f8f2">},</span> 
  <span style="color: #66d9ef">function</span> <span style="color: #f8f8f2">()</span> <span style="color: #f8f8f2">{</span>
    <span style="color: #75715e">// $(this).nextAll().removeClass(&#39;hoverDark&#39;);</span>
    <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #66d9ef">this</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">siblings</span><span style="color: #f8f8f2">().</span><span style="color: #a6e22e">find</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;.carousel-item&quot;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">removeClass</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&#39;hoverDark&#39;</span><span style="color: #f8f8f2">);</span>
  <span style="color: #f8f8f2">}</span>
  <span style="color: #f8f8f2">);</span>


  <span style="color: #75715e">//STOPPING THE CAROUSEL FROM PAUSING ON HOVER</span>
  <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;.carousel&quot;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">carousel</span><span style="color: #f8f8f2">({</span>
    <span style="color: #a6e22e">pause</span><span style="color: rgb(231, 95, 85)">:</span> <span style="color: #e6db74">&quot;false&quot;</span>
  <span style="color: #f8f8f2">});</span>


  <span style="color: #75715e">//ADDING NEW INPUT FIELDS FOR STOCK FORM</span>
  <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(document).</span><span style="color: #a6e22e">ready</span><span style="color: #f8f8f2">(</span><span style="color: #66d9ef">function</span><span style="color: #f8f8f2">()</span> <span style="color: #f8f8f2">{</span>

    <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;#addMore&quot;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">click</span><span style="color: #f8f8f2">(</span><span style="color: #66d9ef">function</span><span style="color: #f8f8f2">(){</span> 
        <span style="color: #66d9ef">var</span> <span style="color: #a6e22e">html</span> <span style="color: rgb(231, 95, 85)">=</span> <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;.copy&quot;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">html</span><span style="color: #f8f8f2">();</span>
        <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;.after-add-more&quot;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">append</span><span style="color: #f8f8f2">(</span><span style="color: #a6e22e">html</span><span style="color: #f8f8f2">);</span>
    <span style="color: #f8f8f2">});</span>

    <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;body&quot;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">on</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;click&quot;</span><span style="color: #f8f8f2">,</span><span style="color: #e6db74">&quot;.remove&quot;</span><span style="color: #f8f8f2">,</span><span style="color: #66d9ef">function</span><span style="color: #f8f8f2">(){</span> 
        <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #66d9ef">this</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">parent</span><span style="color: #f8f8f2">().</span><span style="color: #a6e22e">closest</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;.control-group&quot;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">remove</span><span style="color: #f8f8f2">();</span>
    <span style="color: #f8f8f2">});</span>
  <span style="color: #f8f8f2">});</span>

<span style="color: #75715e">//BOUNCHING ARROW HIDES WHEN SCROLL DOWN</span>
  <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(window).</span><span style="color: #a6e22e">scroll</span><span style="color: #f8f8f2">(</span><span style="color: #66d9ef">function</span><span style="color: #f8f8f2">(){</span>
    <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;.arrow&quot;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">css</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;opacity&quot;</span><span style="color: #f8f8f2">,</span> <span style="color: #ae81ff">1</span> <span style="color: rgb(231, 95, 85)">-</span> <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(window).</span><span style="color: #a6e22e">scrollTop</span><span style="color: #f8f8f2">()</span> <span style="color: rgb(231, 95, 85)">/</span> <span style="color: #ae81ff">250</span><span style="color: #f8f8f2">);</span>
  <span style="color: #f8f8f2">});</span>

<span style="color: #75715e">//TAKES YOU TO AN ID ANCHOR ON EACH PAGE</span>
  <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;#aboutBounceBtn&quot;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">click</span><span style="color: #f8f8f2">(</span><span style="color: #66d9ef">function</span><span style="color: #f8f8f2">()</span> <span style="color: #f8f8f2">{</span>
    <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&#39;html, body&#39;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">animate</span><span style="color: #f8f8f2">({</span>
        <span style="color: #a6e22e">scrollTop</span><span style="color: rgb(231, 95, 85)">:</span> <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;#imgGalleryWrapper&quot;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">offset</span><span style="color: #f8f8f2">().</span><span style="color: #a6e22e">top</span> <span style="color: rgb(231, 95, 85)">-</span> <span style="color: #ae81ff">100</span>
    <span style="color: #f8f8f2">},</span> <span style="color: #ae81ff">2000</span><span style="color: #f8f8f2">);</span>
<span style="color: #f8f8f2">});</span>
<span style="color: #75715e">//TAKES YOU TO AN ID ANCHOR ON THE PAGE</span>
<span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;#equipBounceBtn&quot;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">click</span><span style="color: #f8f8f2">(</span><span style="color: #66d9ef">function</span><span style="color: #f8f8f2">()</span> <span style="color: #f8f8f2">{</span>
  <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&#39;html, body&#39;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">animate</span><span style="color: #f8f8f2">({</span>
      <span style="color: #a6e22e">scrollTop</span><span style="color: rgb(231, 95, 85)">:</span> <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;#panel1&quot;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">offset</span><span style="color: #f8f8f2">().</span><span style="color: #a6e22e">top</span> <span style="color: rgb(231, 95, 85)">-</span> <span style="color: #ae81ff">100</span>
  <span style="color: #f8f8f2">},</span> <span style="color: #ae81ff">2000</span><span style="color: #f8f8f2">);</span>
<span style="color: #f8f8f2">});</span>
<span style="color: #75715e">//TAKES YOU TO AN ID ANCHOR ON THE PAGE</span>
<span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;#clientBounceBtn&quot;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">click</span><span style="color: #f8f8f2">(</span><span style="color: #66d9ef">function</span><span style="color: #f8f8f2">()</span> <span style="color: #f8f8f2">{</span>
  <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&#39;html, body&#39;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">animate</span><span style="color: #f8f8f2">({</span>
      <span style="color: #a6e22e">scrollTop</span><span style="color: rgb(231, 95, 85)">:</span> <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;#imgGalleryWrapper&quot;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">offset</span><span style="color: #f8f8f2">().</span><span style="color: #a6e22e">top</span> <span style="color: rgb(231, 95, 85)">-</span> <span style="color: #ae81ff">100</span>
  <span style="color: #f8f8f2">},</span> <span style="color: #ae81ff">2000</span><span style="color: #f8f8f2">);</span>
<span style="color: #f8f8f2">});</span>
<span style="color: #75715e">//TAKES YOU TO AN ID ANCHOR ON THE PAGE</span>
<span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;#showreelBounceBtn&quot;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">click</span><span style="color: #f8f8f2">(</span><span style="color: #66d9ef">function</span><span style="color: #f8f8f2">()</span> <span style="color: #f8f8f2">{</span>
  <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&#39;html, body&#39;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">animate</span><span style="color: #f8f8f2">({</span>
      <span style="color: #a6e22e">scrollTop</span><span style="color: rgb(231, 95, 85)">:</span> <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;#showreelAnchor&quot;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">offset</span><span style="color: #f8f8f2">().</span><span style="color: #a6e22e">top</span> <span style="color: rgb(231, 95, 85)">-</span> <span style="color: #ae81ff">80</span>
  <span style="color: #f8f8f2">},</span> <span style="color: #ae81ff">2000</span><span style="color: #f8f8f2">);</span>
<span style="color: #f8f8f2">});</span>
<span style="color: #75715e">//TAKES YOU TO AN ID ANCHOR ON THE PAGE</span>
<span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;#contactBounceBtn&quot;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">click</span><span style="color: #f8f8f2">(</span><span style="color: #66d9ef">function</span><span style="color: #f8f8f2">()</span> <span style="color: #f8f8f2">{</span>
  <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&#39;html, body&#39;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">animate</span><span style="color: #f8f8f2">({</span>
      <span style="color: #a6e22e">scrollTop</span><span style="color: rgb(231, 95, 85)">:</span> <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;#contactDetails&quot;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">offset</span><span style="color: #f8f8f2">().</span><span style="color: #a6e22e">top</span> <span style="color: rgb(231, 95, 85)">+</span> <span style="color: #ae81ff">30</span>
  <span style="color: #f8f8f2">},</span> <span style="color: #ae81ff">2000</span><span style="color: #f8f8f2">);</span>
<span style="color: #f8f8f2">});</span>
<span style="color: #75715e">//TAKES YOU TO AN ID ANCHOR ON THE PAGE</span>
<span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;#recceBtn&quot;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">click</span><span style="color: #f8f8f2">(</span><span style="color: #66d9ef">function</span><span style="color: #f8f8f2">()</span> <span style="color: #f8f8f2">{</span>
  <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&#39;html, body&#39;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">animate</span><span style="color: #f8f8f2">({</span>
      <span style="color: #a6e22e">scrollTop</span><span style="color: rgb(231, 95, 85)">:</span> <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;#smallRecce&quot;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">offset</span><span style="color: #f8f8f2">().</span><span style="color: #a6e22e">top</span> <span style="color: rgb(231, 95, 85)">-</span> <span style="color: #ae81ff">20</span>
  <span style="color: #f8f8f2">},</span> <span style="color: #ae81ff">2000</span><span style="color: #f8f8f2">);</span>
<span style="color: #f8f8f2">});</span>
<span style="color: #75715e">//TAKES YOU TO AN ID ANCHOR ON THE PAGE</span>
<span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;#heavyliftBtn&quot;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">click</span><span style="color: #f8f8f2">(</span><span style="color: #66d9ef">function</span><span style="color: #f8f8f2">()</span> <span style="color: #f8f8f2">{</span>
  <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&#39;html, body&#39;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">animate</span><span style="color: #f8f8f2">({</span>
      <span style="color: #a6e22e">scrollTop</span><span style="color: rgb(231, 95, 85)">:</span> <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;#heavylift&quot;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">offset</span><span style="color: #f8f8f2">().</span><span style="color: #a6e22e">top</span> <span style="color: rgb(231, 95, 85)">+</span> <span style="color: #ae81ff">40</span>
  <span style="color: #f8f8f2">},</span> <span style="color: #ae81ff">2000</span><span style="color: #f8f8f2">);</span>
<span style="color: #f8f8f2">});</span>
<span style="color: #75715e">//TAKES YOU TO AN ID ANCHOR ON THE PAGE</span>
<span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;#lightliftBtn&quot;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">click</span><span style="color: #f8f8f2">(</span><span style="color: #66d9ef">function</span><span style="color: #f8f8f2">()</span> <span style="color: #f8f8f2">{</span>
  <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&#39;html, body&#39;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">animate</span><span style="color: #f8f8f2">({</span>
      <span style="color: #a6e22e">scrollTop</span><span style="color: rgb(231, 95, 85)">:</span> <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;#lightlift&quot;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">offset</span><span style="color: #f8f8f2">().</span><span style="color: #a6e22e">top</span> <span style="color: rgb(231, 95, 85)">+</span> <span style="color: #ae81ff">40</span>
  <span style="color: #f8f8f2">},</span> <span style="color: #ae81ff">2000</span><span style="color: #f8f8f2">);</span>
<span style="color: #f8f8f2">});</span>
<span style="color: #75715e">//TAKES YOU TO AN ID ANCHOR ON THE PAGE</span>
<span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;#vehicleBtn&quot;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">click</span><span style="color: #f8f8f2">(</span><span style="color: #66d9ef">function</span><span style="color: #f8f8f2">()</span> <span style="color: #f8f8f2">{</span>
  <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&#39;html, body&#39;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">animate</span><span style="color: #f8f8f2">({</span>
      <span style="color: #a6e22e">scrollTop</span><span style="color: rgb(231, 95, 85)">:</span> <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;#carmount&quot;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">offset</span><span style="color: #f8f8f2">().</span><span style="color: #a6e22e">top</span> <span style="color: rgb(231, 95, 85)">+</span> <span style="color: #ae81ff">40</span>
  <span style="color: #f8f8f2">},</span> <span style="color: #ae81ff">2000</span><span style="color: #f8f8f2">);</span>
<span style="color: #f8f8f2">});</span>
<span style="color: #75715e">//TAKES YOU TO AN ID ANCHOR ON THE PAGE</span>
<span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;#lighttetherBtn&quot;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">click</span><span style="color: #f8f8f2">(</span><span style="color: #66d9ef">function</span><span style="color: #f8f8f2">()</span> <span style="color: #f8f8f2">{</span>
  <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&#39;html, body&#39;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">animate</span><span style="color: #f8f8f2">({</span>
      <span style="color: #a6e22e">scrollTop</span><span style="color: rgb(231, 95, 85)">:</span> <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;#lighttether&quot;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">offset</span><span style="color: #f8f8f2">().</span><span style="color: #a6e22e">top</span> <span style="color: rgb(231, 95, 85)">+</span> <span style="color: #ae81ff">40</span>
  <span style="color: #f8f8f2">},</span> <span style="color: #ae81ff">2000</span><span style="color: #f8f8f2">);</span>
<span style="color: #f8f8f2">});</span>
<span style="color: #75715e">//TAKES YOU TO AN ID ANCHOR ON THE PAGE</span>
<span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;#specialsystemsBtn&quot;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">click</span><span style="color: #f8f8f2">(</span><span style="color: #66d9ef">function</span><span style="color: #f8f8f2">()</span> <span style="color: #f8f8f2">{</span>
  <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&#39;html, body&#39;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">animate</span><span style="color: #f8f8f2">({</span>
      <span style="color: #a6e22e">scrollTop</span><span style="color: rgb(231, 95, 85)">:</span> <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;#specialsystems&quot;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">offset</span><span style="color: #f8f8f2">().</span><span style="color: #a6e22e">top</span> <span style="color: rgb(231, 95, 85)">+</span> <span style="color: #ae81ff">40</span>
  <span style="color: #f8f8f2">},</span> <span style="color: #ae81ff">2000</span><span style="color: #f8f8f2">);</span>
<span style="color: #f8f8f2">});</span>



<span style="color: #75715e">//ENABLES THE SEND MESSAGE BUTTON IN CONTACT US WHEN INPUTS ARE FILLED IN</span>
<span style="color: #66d9ef">function</span> <span style="color: #a6e22e">manage</span><span style="color: #f8f8f2">()</span> <span style="color: #f8f8f2">{</span>
  <span style="color: #66d9ef">var</span> <span style="color: #a6e22e">bt</span> <span style="color: rgb(231, 95, 85)">=</span> <span style="color: #f8f8f2">document.</span><span style="color: #a6e22e">getElementById</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&#39;contactSendBtnBtn&#39;</span><span style="color: #f8f8f2">);</span>
  <span style="color: #66d9ef">if</span> <span style="color: #f8f8f2">(</span><span style="color: #a6e22e">nameInput</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">value</span> <span style="color: rgb(231, 95, 85)">!=</span> <span style="color: #e6db74">&#39;&#39;</span> <span style="color: rgb(231, 95, 85)">&amp;&amp;</span> <span style="color: #a6e22e">messageInput</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">value</span> <span style="color: rgb(231, 95, 85)">!=</span> <span style="color: #e6db74">&#39;&#39;</span> <span style="color: rgb(231, 95, 85)">&amp;&amp;</span> <span style="color: #a6e22e">emailInput</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">value</span> <span style="color: rgb(231, 95, 85)">!=</span> <span style="color: #e6db74">&#39;&#39;</span><span style="color: #f8f8f2">)</span> 
  <span style="color: #f8f8f2">{</span>
      <span style="color: #a6e22e">bt</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">disabled</span> <span style="color: rgb(231, 95, 85)">=</span> <span style="color: #66d9ef">false</span><span style="color: #f8f8f2">;</span>
  <span style="color: #f8f8f2">}</span>
  <span style="color: #66d9ef">else</span> <span style="color: #f8f8f2">{</span>
      <span style="color: #a6e22e">bt</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">disabled</span> <span style="color: rgb(231, 95, 85)">=</span> <span style="color: #66d9ef">true</span><span style="color: #f8f8f2">;</span>
  <span style="color: #f8f8f2">}</span>
<span style="color: #f8f8f2">}</span>

<span style="color: #75715e">//UNDISABLES THE SEND MESSAGE BUTTON IN STOCK WHEN INPUTS ARE FILLED IN (this is same as above only with jquery instead of vanilla JS)</span>
<span style="color: #66d9ef">function</span> <span style="color: #a6e22e">filledIn</span><span style="color: #f8f8f2">()</span> <span style="color: #f8f8f2">{</span>
  <span style="color: #66d9ef">let</span> <span style="color: #a6e22e">btn</span> <span style="color: rgb(231, 95, 85)">=</span> <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;#btnStockSubmit&quot;</span><span style="color: #f8f8f2">);</span>
  <span style="color: #66d9ef">let</span> <span style="color: #a6e22e">request</span> <span style="color: rgb(231, 95, 85)">=</span> <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&#39;select&#39;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">on</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&#39;change&#39;</span><span style="color: #f8f8f2">,</span> <span style="color: #66d9ef">function</span><span style="color: #f8f8f2">()</span> <span style="color: #f8f8f2">{</span>
    <span style="color: #f8f8f2">(</span> <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #66d9ef">this</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">find</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;:selected&quot;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">val</span><span style="color: #f8f8f2">()</span> <span style="color: #f8f8f2">);</span>
  <span style="color: #f8f8f2">});</span>

  <span style="color: #66d9ef">if</span><span style="color: #f8f8f2">(</span><span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;#nameInput&quot;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">val</span><span style="color: #f8f8f2">()</span> <span style="color: rgb(231, 95, 85)">!=</span> <span style="color: #e6db74">&#39;&#39;</span> <span style="color: rgb(231, 95, 85)">&amp;&amp;</span> <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;#emailInput&quot;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">val</span><span style="color: #f8f8f2">()</span> <span style="color: rgb(231, 95, 85)">!=</span> <span style="color: #e6db74">&#39;&#39;</span> <span style="color: rgb(231, 95, 85)">&amp;&amp;</span> 
  <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #a6e22e">request</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">val</span><span style="color: #f8f8f2">()</span> <span style="color: rgb(231, 95, 85)">!==</span> <span style="color: #e6db74">&quot;Stock Section...*&quot;</span> <span style="color: rgb(231, 95, 85)">&amp;&amp;</span> <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;#tcIn&quot;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">val</span><span style="color: #f8f8f2">()</span> <span style="color: rgb(231, 95, 85)">!=</span> <span style="color: #e6db74">&#39;&#39;</span> <span style="color: rgb(231, 95, 85)">&amp;&amp;</span> <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;#tcOut&quot;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">val</span><span style="color: #f8f8f2">()</span> <span style="color: rgb(231, 95, 85)">!=</span> <span style="color: #e6db74">&#39;&#39;</span><span style="color: #f8f8f2">)</span> <span style="color: #f8f8f2">{</span>

    <span style="color: #a6e22e">btn</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">attr</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;disabled&quot;</span><span style="color: #f8f8f2">,</span> <span style="color: #66d9ef">false</span><span style="color: #f8f8f2">);</span>
  <span style="color: #f8f8f2">}</span>
  <span style="color: #66d9ef">else</span> <span style="color: #f8f8f2">{</span>
    <span style="color: #a6e22e">btn</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">attr</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;disabled&quot;</span><span style="color: #f8f8f2">,</span> <span style="color: #66d9ef">true</span><span style="color: #f8f8f2">);</span>
  <span style="color: #f8f8f2">};</span>
  
<span style="color: #f8f8f2">};</span>


<span style="color: #75715e">//MOVING THE SELECTED CLASS TO THE CORRECT SELECTED OPTION</span>
<span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(document).</span><span style="color: #a6e22e">on</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;change&quot;</span><span style="color: #f8f8f2">,</span><span style="color: #e6db74">&quot;select&quot;</span><span style="color: #f8f8f2">,</span><span style="color: #66d9ef">function</span><span style="color: #f8f8f2">(){</span>
  <span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;option[value=&quot;</span> <span style="color: rgb(231, 95, 85)">+</span> <span style="color: #66d9ef">this</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">value</span> <span style="color: rgb(231, 95, 85)">+</span> <span style="color: #e6db74">&quot;]&quot;</span><span style="color: #f8f8f2">,</span> <span style="color: #66d9ef">this</span><span style="color: #f8f8f2">)</span>
  <span style="color: #f8f8f2">.</span><span style="color: #a6e22e">attr</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;selected&quot;</span><span style="color: #f8f8f2">,</span> <span style="color: #66d9ef">true</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">siblings</span><span style="color: #f8f8f2">()</span>
  <span style="color: #f8f8f2">.</span><span style="color: #a6e22e">removeAttr</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;selected&quot;</span><span style="color: #f8f8f2">)</span>
<span style="color: #f8f8f2">});</span>


<span style="color: #75715e">//MAKING THE TOP LOGO TAKE YOU BACK TO HOME</span>
<span style="color: #a6e22e">$</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;#logo-main&quot;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">click</span><span style="color: #f8f8f2">(</span><span style="color: #66d9ef">function</span><span style="color: #f8f8f2">()</span> <span style="color: #f8f8f2">{</span>
  <span style="color: #f8f8f2">window.</span><span style="color: #a6e22e">location</span><span style="color: rgb(231, 95, 85)">=</span><span style="color: #e6db74">&quot;index.php&quot;</span><span style="color: #f8f8f2">;</span>
<span style="color: #f8f8f2">});</span>



<span style="color: #75715e">// $(window).on(&#39;load&#39;, function(){</span>
<span style="color: #75715e">//   $(&quot;#modalStockThanks&quot;).modal(&#39;show&#39;);</span>
<span style="color: #75715e">// })</span>


<span style="color: #75715e">// $(&quot;#stockRequestWrapper&quot;).submit(function(e) {</span>
<span style="color: #75715e">//   e.preventDefault();</span>

<span style="color: #75715e">//   //AJAX request</span>
<span style="color: #75715e">//   $.ajax({</span>
<span style="color: #75715e">//     type : &quot;post&quot;,</span>
<span style="color: #75715e">//     url : &quot;showreelstock.php&quot;,</span>
<span style="color: #75715e">//     data : $(&quot;#stockRequestWrapper&quot;).serialize(),</span>
<span style="color: #75715e">//     success : function() {</span>
<span style="color: #75715e">//       console.log(&quot;Success&quot;);</span>
<span style="color: #75715e">//     },</span>
<span style="color: #75715e">//     error: function() {</span>
<span style="color: #75715e">//       console.log(&quot;Error&quot;);</span>
<span style="color: #75715e">//     }</span>
    
<span style="color: #75715e">//   });</span>
<span style="color: #75715e">// });</span>
</pre></div>
