<!-- HTML generated using hilite.me --><div style="background: #272822; overflow:auto;width:auto;border:solid gray;border-width:.1em .1em .1em .8em;padding:.2em .6em;"><pre style="margin: 0; line-height: 125%"><span style="color: #f92672">@</span><span style="color: #f8f8f2">extends</span><span style="color: #f92672">(</span><span style="color: #960050; background-color: #1e0010">&#39;</span><span style="color: #f8f8f2">layouts</span><span style="color: #f92672">.</span><span style="color: #f8f8f2">app</span><span style="color: #960050; background-color: #1e0010">&#39;</span><span style="color: #f92672">)</span>

<span style="color: #f92672">@</span><span style="color: #f8f8f2">section</span><span style="color: #f92672">(</span><span style="color: #960050; background-color: #1e0010">&#39;</span><span style="color: #f8f8f2">content</span><span style="color: #960050; background-color: #1e0010">&#39;</span><span style="color: #f92672">)</span>
<span style="color: #f92672">&lt;</span><span style="color: #f8f8f2">div</span> <span style="color: #f8f8f2">class</span><span style="color: #f92672">=</span><span style="color: #e6db74">&quot;container&quot;</span><span style="color: #f92672">&gt;</span>
    <span style="color: #f92672">&lt;</span><span style="color: #f8f8f2">div</span> <span style="color: #f8f8f2">class</span><span style="color: #f92672">=</span><span style="color: #e6db74">&quot;row&quot;</span><span style="color: #f92672">&gt;</span>
        <span style="color: #f92672">&lt;</span><span style="color: #f8f8f2">div</span> <span style="color: #f8f8f2">class</span><span style="color: #f92672">=</span><span style="color: #e6db74">&quot;col-8&quot;</span><span style="color: #f92672">&gt;</span>
            <span style="color: #f92672">&lt;</span><span style="color: #f8f8f2">img</span> <span style="color: #f8f8f2">src</span><span style="color: #f92672">=</span><span style="color: #e6db74">&quot;/storage/{{ $post-&gt;image }}&quot;</span> <span style="color: #f8f8f2">alt</span><span style="color: #f92672">=</span><span style="color: #e6db74">&quot;&quot;</span> <span style="color: #f8f8f2">class</span><span style="color: #f92672">=</span><span style="color: #e6db74">&quot;w-100&quot;</span><span style="color: #f92672">&gt;</span>
        <span style="color: #f92672">&lt;/</span><span style="color: #f8f8f2">div</span><span style="color: #f92672">&gt;</span>
        <span style="color: #f92672">&lt;</span><span style="color: #f8f8f2">div</span> <span style="color: #f8f8f2">class</span><span style="color: #f92672">=</span><span style="color: #e6db74">&quot;col-4&quot;</span><span style="color: #f92672">&gt;</span>
            <span style="color: #f92672">&lt;</span><span style="color: #f8f8f2">div</span> <span style="color: #f8f8f2">class</span><span style="color: #f92672">=</span><span style="color: #e6db74">&quot;d-flex align-items-center&quot;</span><span style="color: #f92672">&gt;</span>
                <span style="color: #f92672">&lt;</span><span style="color: #f8f8f2">div</span> <span style="color: #f8f8f2">class</span><span style="color: #f92672">=</span><span style="color: #e6db74">&quot;mr-3&quot;</span><span style="color: #f92672">&gt;</span>
                    <span style="color: #f92672">&lt;</span><span style="color: #f8f8f2">img</span> <span style="color: #f8f8f2">src</span><span style="color: #f92672">=</span><span style="color: #e6db74">&quot;{{ $post-&gt;user-&gt;profile-&gt;profileImage() }}&quot;</span> <span style="color: #f8f8f2">class</span><span style="color: #f92672">=</span><span style="color: #e6db74">&quot;w-100 rounded-circle&quot;</span> <span style="color: #f8f8f2">style</span><span style="color: #f92672">=</span><span style="color: #e6db74">&quot;max-width: 40px&quot;</span><span style="color: #f92672">&gt;</span>
                <span style="color: #f92672">&lt;/</span><span style="color: #f8f8f2">div</span><span style="color: #f92672">&gt;</span>
                <span style="color: #f92672">&lt;</span><span style="color: #f8f8f2">div</span><span style="color: #f92672">&gt;</span>
                   <span style="color: #f92672">&lt;</span><span style="color: #f8f8f2">span</span> <span style="color: #f8f8f2">class</span><span style="color: #f92672">=</span><span style="color: #e6db74">&quot;font-weight-bold&quot;</span><span style="color: #f92672">&gt;</span>
                       <span style="color: #f92672">&lt;</span><span style="color: #f8f8f2">a</span> <span style="color: #f8f8f2">href</span><span style="color: #f92672">=</span><span style="color: #e6db74">&quot;/profile/{{ $post-&gt;user-&gt;id }}&quot;</span> <span style="color: #f8f8f2">class</span><span style="color: #f92672">=</span><span style="color: #e6db74">&quot;text-dark&quot;</span><span style="color: #f92672">&gt;{{</span> <span style="color: #960050; background-color: #1e0010">$</span><span style="color: #f8f8f2">post</span><span style="color: #f92672">-&gt;</span><span style="color: #f8f8f2">user</span><span style="color: #f92672">-&gt;</span><span style="color: #f8f8f2">username</span> <span style="color: #f92672">}}&lt;/</span><span style="color: #f8f8f2">a</span><span style="color: #f92672">&gt;</span>
                    <span style="color: #f92672">&lt;/</span><span style="color: #f8f8f2">span</span><span style="color: #f92672">&gt;</span>
                    <span style="color: #f92672">&lt;</span><span style="color: #f8f8f2">a</span> <span style="color: #f8f8f2">href</span><span style="color: #f92672">=</span><span style="color: #e6db74">&quot;#&quot;</span> <span style="color: #f8f8f2">class</span><span style="color: #f92672">=</span><span style="color: #e6db74">&quot;font-weight-bold ml-2&quot;</span><span style="color: #f92672">&gt;&amp;</span><span style="color: #75715e">#8249; Follow&lt;/a&gt;</span>
                <span style="color: #f92672">&lt;/</span><span style="color: #f8f8f2">div</span><span style="color: #f92672">&gt;</span>
            <span style="color: #f92672">&lt;/</span><span style="color: #f8f8f2">div</span><span style="color: #f92672">&gt;</span>
            <span style="color: #f92672">&lt;</span><span style="color: #f8f8f2">hr</span><span style="color: #f92672">&gt;</span>
            <span style="color: #f92672">&lt;</span><span style="color: #f8f8f2">div</span> <span style="color: #f8f8f2">class</span><span style="color: #f92672">=</span><span style="color: #e6db74">&quot;mt-3&quot;</span><span style="color: #f92672">&gt;</span>
                <span style="color: #f92672">&lt;</span><span style="color: #f8f8f2">p</span><span style="color: #f92672">&gt;</span>
                    <span style="color: #f92672">&lt;</span><span style="color: #f8f8f2">span</span> <span style="color: #f8f8f2">class</span><span style="color: #f92672">=</span><span style="color: #e6db74">&quot;font-weight-bold pr-2&quot;</span><span style="color: #f92672">&gt;</span>
                        <span style="color: #f92672">&lt;</span><span style="color: #f8f8f2">a</span> <span style="color: #f8f8f2">href</span><span style="color: #f92672">=</span><span style="color: #e6db74">&quot;/profile/{{ $post-&gt;user-&gt;id }}&quot;</span> <span style="color: #f8f8f2">class</span><span style="color: #f92672">=</span><span style="color: #e6db74">&quot;text-dark&quot;</span><span style="color: #f92672">&gt;{{</span> <span style="color: #960050; background-color: #1e0010">$</span><span style="color: #f8f8f2">post</span><span style="color: #f92672">-&gt;</span><span style="color: #f8f8f2">user</span><span style="color: #f92672">-&gt;</span><span style="color: #f8f8f2">username</span> <span style="color: #f92672">}}&lt;/</span><span style="color: #f8f8f2">a</span><span style="color: #f92672">&gt;</span>
                    <span style="color: #f92672">&lt;/</span><span style="color: #f8f8f2">span</span><span style="color: #f92672">&gt;|</span>
                    <span style="color: #f92672">{{</span> <span style="color: #960050; background-color: #1e0010">$</span><span style="color: #f8f8f2">post</span><span style="color: #f92672">-&gt;</span><span style="color: #f8f8f2">caption</span> <span style="color: #f92672">}}</span>
                <span style="color: #f92672">&lt;/</span><span style="color: #f8f8f2">p</span><span style="color: #f92672">&gt;</span>
            <span style="color: #f92672">&lt;/</span><span style="color: #f8f8f2">div</span><span style="color: #f92672">&gt;</span>
        <span style="color: #f92672">&lt;/</span><span style="color: #f8f8f2">div</span><span style="color: #f92672">&gt;</span>
    <span style="color: #f92672">&lt;/</span><span style="color: #f8f8f2">div</span><span style="color: #f92672">&gt;</span>

<span style="color: #f92672">&lt;/</span><span style="color: #f8f8f2">div</span><span style="color: #f92672">&gt;</span>
<span style="color: #f92672">@</span><span style="color: #f8f8f2">endsection</span>
</pre></div>
