<!-- HTML generated using hilite.me --><div style="background: #272822; overflow:auto;width:auto;border:solid gray;border-width:.1em .1em .1em .8em;padding:.2em .6em;"><pre style="margin: 0; line-height: 125%"><span style="color: #f92672">&lt;</span><span style="color: #960050; background-color: #1e0010">?</span><span style="color: #f8f8f2">php</span>

<span style="color: #f8f8f2">use</span> <span style="color: #a6e22e">Illuminate</span><span style="color: #f92672">\</span><span style="color: #a6e22e">Support</span><span style="color: #f92672">\</span><span style="color: #a6e22e">Facades</span><span style="color: #f92672">\</span><span style="color: #a6e22e">Route</span><span style="color: #f8f8f2">;</span>
<span style="color: #f8f8f2">use</span> <span style="color: #a6e22e">App</span><span style="color: #f92672">\</span><span style="color: #a6e22e">Mail</span><span style="color: #f92672">\</span><span style="color: #a6e22e">ThanksForSigningUp_noreply</span><span style="color: #f8f8f2">;</span>

<span style="color: #f92672">/*</span>
<span style="color: #960050; background-color: #1e0010">|</span><span style="color: #75715e">--------------------------------------------------------------------------</span>
<span style="color: #960050; background-color: #1e0010">|</span> <span style="color: #a6e22e">Web</span> <span style="color: #a6e22e">Routes</span>
<span style="color: #960050; background-color: #1e0010">|</span><span style="color: #75715e">--------------------------------------------------------------------------</span>
<span style="color: #960050; background-color: #1e0010">|</span>
<span style="color: #960050; background-color: #1e0010">|</span> <span style="color: #a6e22e">Here</span> <span style="color: #f8f8f2">is</span> <span style="color: #f8f8f2">where</span> <span style="color: #f8f8f2">you</span> <span style="color: #f8f8f2">can</span> <span style="color: #f8f8f2">register</span> <span style="color: #f8f8f2">web</span> <span style="color: #f8f8f2">routes</span> <span style="color: #66d9ef">for</span> <span style="color: #f8f8f2">your</span> <span style="color: #f8f8f2">application</span><span style="color: #f92672">.</span> <span style="color: #a6e22e">These</span>
<span style="color: #960050; background-color: #1e0010">|</span> <span style="color: #f8f8f2">routes</span> <span style="color: #f8f8f2">are</span> <span style="color: #f8f8f2">loaded</span> <span style="color: #f8f8f2">by</span> <span style="color: #f8f8f2">the</span> <span style="color: #a6e22e">RouteServiceProvider</span> <span style="color: #f8f8f2">within</span> <span style="color: #f8f8f2">a</span> <span style="color: #f8f8f2">group</span> <span style="color: #f8f8f2">which</span>
<span style="color: #960050; background-color: #1e0010">|</span> <span style="color: #f8f8f2">contains</span> <span style="color: #f8f8f2">the</span> <span style="color: #e6db74">&quot;web&quot;</span> <span style="color: #f8f8f2">middleware</span> <span style="color: #f8f8f2">group</span><span style="color: #f92672">.</span> <span style="color: #a6e22e">Now</span> <span style="color: #f8f8f2">create</span> <span style="color: #f8f8f2">something</span> <span style="color: #f8f8f2">great</span><span style="color: #f92672">!</span>
    <span style="color: #a6e22e">ROUTE</span> <span style="color: #a6e22e">ORDER</span> <span style="color: #a6e22e">IS</span> <span style="color: #a6e22e">IMPORTANT</span> <span style="color: #f92672">-</span> <span style="color: #a6e22e">ANYTHING</span> <span style="color: #a6e22e">WITH</span> <span style="color: #a6e22e">VARIABLE</span> <span style="color: #a6e22e">SHOULD</span> <span style="color: #a6e22e">GO</span> <span style="color: #a6e22e">LAST</span>
<span style="color: #960050; background-color: #1e0010">|</span>
<span style="color: #f92672">*/</span>

<span style="color: #f8f8f2">Route::get</span><span style="color: #66d9ef">(</span><span style="color: #e6db74">&#39;/&#39;</span><span style="color: #f8f8f2">,</span> <span style="color: #f8f8f2">function</span> <span style="color: #66d9ef">()</span> <span style="color: #66d9ef">{</span>
    <span style="color: #66d9ef">return</span> <span style="color: #f8f8f2">view</span><span style="color: #66d9ef">(</span><span style="color: #e6db74">&#39;welcome&#39;</span><span style="color: #66d9ef">)</span><span style="color: #f8f8f2">;</span>
<span style="color: #66d9ef">})</span><span style="color: #f8f8f2">;</span>

<span style="color: #f8f8f2">Auth::routes</span><span style="color: #66d9ef">()</span><span style="color: #f8f8f2">;</span>

<span style="color: #f8f8f2">Route::get</span><span style="color: #66d9ef">(</span><span style="color: #e6db74">&#39;/email&#39;</span><span style="color: #f8f8f2">,</span> <span style="color: #f8f8f2">function</span> <span style="color: #66d9ef">()</span> <span style="color: #66d9ef">{</span>
    <span style="color: #66d9ef">return</span> <span style="color: #f8f8f2">new</span> <span style="color: #a6e22e">ThanksForSigningUp_noreply</span><span style="color: #66d9ef">()</span><span style="color: #f8f8f2">;</span> 
<span style="color: #66d9ef">})</span><span style="color: #f8f8f2">;</span>


<span style="color: #f8f8f2">Route::POST</span><span style="color: #66d9ef">(</span><span style="color: #e6db74">&#39;follow/{user}&#39;</span><span style="color: #f8f8f2">,</span> <span style="color: #e6db74">&#39;App\Http\Controllers\FollowsController@store&#39;</span><span style="color: #66d9ef">)</span><span style="color: #f8f8f2">;</span>

<span style="color: #f8f8f2">Route::get</span><span style="color: #66d9ef">(</span><span style="color: #e6db74">&#39;/&#39;</span><span style="color: #f8f8f2">,</span> <span style="color: #e6db74">&#39;App\Http\Controllers\PostsController@index&#39;</span><span style="color: #66d9ef">)</span><span style="color: #f8f8f2">;</span>
<span style="color: #f8f8f2">Route::get</span><span style="color: #66d9ef">(</span><span style="color: #e6db74">&#39;/p/create&#39;</span><span style="color: #f8f8f2">,</span> <span style="color: #e6db74">&#39;App\Http\Controllers\PostsController@create&#39;</span><span style="color: #66d9ef">)</span><span style="color: #f8f8f2">;</span>
<span style="color: #f8f8f2">Route::POST</span><span style="color: #66d9ef">(</span><span style="color: #e6db74">&#39;/p&#39;</span><span style="color: #f8f8f2">,</span> <span style="color: #e6db74">&#39;App\Http\Controllers\PostsController@store&#39;</span><span style="color: #66d9ef">)</span><span style="color: #f8f8f2">;</span>
<span style="color: #f8f8f2">Route::get</span><span style="color: #66d9ef">(</span><span style="color: #e6db74">&#39;/p/{post}&#39;</span><span style="color: #f8f8f2">,</span> <span style="color: #e6db74">&#39;App\Http\Controllers\PostsController@show&#39;</span><span style="color: #66d9ef">)</span><span style="color: #f8f8f2">;</span>



<span style="color: #f8f8f2">Route::get</span><span style="color: #66d9ef">(</span><span style="color: #e6db74">&#39;/profile/{user}&#39;</span><span style="color: #f8f8f2">,</span> <span style="color: #66d9ef">[</span><span style="color: #a6e22e">App</span><span style="color: #f92672">\</span><span style="color: #a6e22e">Http</span><span style="color: #f92672">\</span><span style="color: #a6e22e">Controllers</span><span style="color: #f92672">\</span><span style="color: #f8f8f2">ProfilesController::class,</span> <span style="color: #e6db74">&#39;index&#39;</span><span style="color: #66d9ef">])</span><span style="color: #a6e22e">-&gt;</span><span style="color: #f8f8f2">name</span><span style="color: #66d9ef">(</span><span style="color: #e6db74">&#39;profile.show&#39;</span><span style="color: #66d9ef">)</span><span style="color: #f8f8f2">;</span>
<span style="color: #f8f8f2">Route::get</span><span style="color: #66d9ef">(</span><span style="color: #e6db74">&#39;/profile/{user}/edit&#39;</span><span style="color: #f8f8f2">,</span> <span style="color: #66d9ef">[</span><span style="color: #a6e22e">App</span><span style="color: #f92672">\</span><span style="color: #a6e22e">Http</span><span style="color: #f92672">\</span><span style="color: #a6e22e">Controllers</span><span style="color: #f92672">\</span><span style="color: #f8f8f2">ProfilesController::class,</span> <span style="color: #e6db74">&#39;edit&#39;</span><span style="color: #66d9ef">])</span><span style="color: #a6e22e">-&gt;</span><span style="color: #f8f8f2">name</span><span style="color: #66d9ef">(</span><span style="color: #e6db74">&#39;profile.edit&#39;</span><span style="color: #66d9ef">)</span><span style="color: #f8f8f2">;</span>
<span style="color: #f8f8f2">Route::PATCH</span><span style="color: #66d9ef">(</span><span style="color: #e6db74">&#39;/profile/{user}&#39;</span><span style="color: #f8f8f2">,</span> <span style="color: #66d9ef">[</span><span style="color: #a6e22e">App</span><span style="color: #f92672">\</span><span style="color: #a6e22e">Http</span><span style="color: #f92672">\</span><span style="color: #a6e22e">Controllers</span><span style="color: #f92672">\</span><span style="color: #f8f8f2">ProfilesController::class,</span> <span style="color: #e6db74">&#39;update&#39;</span><span style="color: #66d9ef">])</span><span style="color: #a6e22e">-&gt;</span><span style="color: #f8f8f2">name</span><span style="color: #66d9ef">(</span><span style="color: #e6db74">&#39;profile.update&#39;</span><span style="color: #66d9ef">)</span><span style="color: #f8f8f2">;</span>
</pre></div>
