<!-- HTML generated using hilite.me --><div style="background: #272822; overflow:auto;width:auto;border:solid gray;border-width:.1em .1em .1em .8em;padding:.2em .6em;"><pre style="margin: 0; line-height: 125%"><span style="color: #f92672">@</span><span style="color: #f8f8f2">extends</span><span style="color: #f92672">(</span><span style="color: #960050; background-color: #1e0010">&#39;</span><span style="color: #f8f8f2">layouts</span><span style="color: #f92672">.</span><span style="color: #f8f8f2">app</span><span style="color: #960050; background-color: #1e0010">&#39;</span><span style="color: #f92672">)</span>

<span style="color: #f92672">@</span><span style="color: #f8f8f2">section</span><span style="color: #f92672">(</span><span style="color: #960050; background-color: #1e0010">&#39;</span><span style="color: #f8f8f2">content</span><span style="color: #960050; background-color: #1e0010">&#39;</span><span style="color: #f92672">)</span>
<span style="color: #f92672">&lt;</span><span style="color: #f8f8f2">div</span> <span style="color: #f8f8f2">class</span><span style="color: #f92672">=</span><span style="color: #e6db74">&quot;container&quot;</span><span style="color: #f92672">&gt;</span>
    <span style="color: #f92672">&lt;</span><span style="color: #f8f8f2">form</span> <span style="color: #f8f8f2">action</span><span style="color: #f92672">=</span><span style="color: #e6db74">&quot;/p&quot;</span> <span style="color: #f8f8f2">enctype</span><span style="color: #f92672">=</span><span style="color: #e6db74">&quot;multipart/form-data&quot;</span> <span style="color: #66d9ef">method</span><span style="color: #f92672">=</span><span style="color: #e6db74">&quot;POST&quot;</span><span style="color: #f92672">&gt;</span>
        <span style="color: #f92672">@</span><span style="color: #f8f8f2">csrf</span>

        <span style="color: #f92672">&lt;</span><span style="color: #f8f8f2">div</span> <span style="color: #f8f8f2">class</span><span style="color: #f92672">=</span><span style="color: #e6db74">&quot;row&quot;</span><span style="color: #f92672">&gt;</span>
            <span style="color: #f92672">&lt;</span><span style="color: #f8f8f2">div</span> <span style="color: #f8f8f2">class</span><span style="color: #f92672">=</span><span style="color: #e6db74">&quot;col-8 offset-2&quot;</span><span style="color: #f92672">&gt;</span>

                <span style="color: #f92672">&lt;</span><span style="color: #f8f8f2">div</span> <span style="color: #f8f8f2">class</span><span style="color: #f92672">=</span><span style="color: #e6db74">&quot;row&quot;</span><span style="color: #f92672">&gt;</span>
                    <span style="color: #f92672">&lt;</span><span style="color: #f8f8f2">h1</span><span style="color: #f92672">&gt;</span><span style="color: #f8f8f2">Add</span> <span style="color: #f8f8f2">New</span> <span style="color: #f8f8f2">Post</span><span style="color: #f92672">&lt;/</span><span style="color: #f8f8f2">h1</span><span style="color: #f92672">&gt;</span>
                <span style="color: #f92672">&lt;/</span><span style="color: #f8f8f2">div</span><span style="color: #f92672">&gt;</span>

                <span style="color: #f92672">&lt;</span><span style="color: #f8f8f2">div</span> <span style="color: #f8f8f2">class</span><span style="color: #f92672">=</span><span style="color: #e6db74">&quot;form-group row&quot;</span><span style="color: #f92672">&gt;</span>
                    <span style="color: #f92672">&lt;</span><span style="color: #f8f8f2">label</span> <span style="color: #66d9ef">for</span><span style="color: #f92672">=</span><span style="color: #e6db74">&quot;caption&quot;</span> <span style="color: #f8f8f2">class</span><span style="color: #f92672">=</span><span style="color: #e6db74">&quot;col-md-4 col-form-label &quot;</span><span style="color: #f92672">&gt;</span><span style="color: #f8f8f2">Post</span> <span style="color: #f8f8f2">Caption</span><span style="color: #f92672">&lt;/</span><span style="color: #f8f8f2">label</span><span style="color: #f92672">&gt;</span>
                        <span style="color: #f92672">&lt;</span><span style="color: #f8f8f2">input</span> <span style="color: #f8f8f2">id</span><span style="color: #f92672">=</span><span style="color: #e6db74">&quot;caption&quot;</span>
                                <span style="color: #f8f8f2">type</span><span style="color: #f92672">=</span><span style="color: #e6db74">&quot;text&quot;</span>
                                <span style="color: #f8f8f2">class</span><span style="color: #f92672">=</span><span style="color: #e6db74">&quot;form-control</span>
<span style="color: #e6db74">                                @error(&#39;caption&#39;) is-invalid @enderror&quot;</span>
                                <span style="color: #f8f8f2">name</span><span style="color: #f92672">=</span><span style="color: #e6db74">&quot;caption&quot;</span>
                                <span style="color: #f8f8f2">value</span><span style="color: #f92672">=</span><span style="color: #e6db74">&quot;{{ old(&#39;caption&#39;) }}&quot;</span>
                                <span style="color: #f8f8f2">autocomplete</span><span style="color: #f92672">=</span><span style="color: #e6db74">&quot;caption&quot;</span> <span style="color: #f8f8f2">autofocus</span><span style="color: #f92672">&gt;</span>
                        <span style="color: #f92672">@</span><span style="color: #f8f8f2">error</span><span style="color: #f92672">(</span><span style="color: #960050; background-color: #1e0010">&#39;</span><span style="color: #f8f8f2">caption</span><span style="color: #960050; background-color: #1e0010">&#39;</span><span style="color: #f92672">)</span>
                            <span style="color: #f92672">&lt;</span><span style="color: #f8f8f2">span</span> <span style="color: #f8f8f2">class</span><span style="color: #f92672">=</span><span style="color: #e6db74">&quot;invalid-feedback&quot;</span> <span style="color: #f8f8f2">role</span><span style="color: #f92672">=</span><span style="color: #e6db74">&quot;alert&quot;</span><span style="color: #f92672">&gt;</span>
                                <span style="color: #f92672">&lt;</span><span style="color: #f8f8f2">strong</span><span style="color: #f92672">&gt;{{</span> <span style="color: #960050; background-color: #1e0010">$</span><span style="color: #f8f8f2">message</span> <span style="color: #f92672">}}&lt;/</span><span style="color: #f8f8f2">strong</span><span style="color: #f92672">&gt;</span>
                            <span style="color: #f92672">&lt;/</span><span style="color: #f8f8f2">span</span><span style="color: #f92672">&gt;</span>
                        <span style="color: #f92672">@</span><span style="color: #f8f8f2">enderror</span>
                <span style="color: #f92672">&lt;/</span><span style="color: #f8f8f2">div</span><span style="color: #f92672">&gt;</span>


                <span style="color: #f92672">&lt;</span><span style="color: #f8f8f2">div</span> <span style="color: #f8f8f2">class</span><span style="color: #f92672">=</span><span style="color: #e6db74">&quot;row&quot;</span><span style="color: #f92672">&gt;</span>
                    <span style="color: #f92672">&lt;</span><span style="color: #f8f8f2">label</span> <span style="color: #66d9ef">for</span><span style="color: #f92672">=</span><span style="color: #e6db74">&quot;image&quot;</span> <span style="color: #f8f8f2">class</span><span style="color: #f92672">=</span><span style="color: #e6db74">&quot;col-md-4 col-form-label &quot;</span><span style="color: #f92672">&gt;</span><span style="color: #f8f8f2">Post</span> <span style="color: #f8f8f2">Image</span><span style="color: #f92672">&lt;/</span><span style="color: #f8f8f2">label</span><span style="color: #f92672">&gt;</span>
                    <span style="color: #f92672">&lt;</span><span style="color: #f8f8f2">input</span> <span style="color: #f8f8f2">type</span><span style="color: #f92672">=</span><span style="color: #e6db74">&quot;file&quot;</span> <span style="color: #f8f8f2">class</span><span style="color: #f92672">=</span><span style="color: #e6db74">&quot;form-control-file&quot;</span> <span style="color: #f8f8f2">id</span><span style="color: #f92672">=</span><span style="color: #e6db74">&quot;image&quot;</span> <span style="color: #f8f8f2">name</span><span style="color: #f92672">=</span><span style="color: #e6db74">&quot;image&quot;</span><span style="color: #f92672">&gt;</span>

                    <span style="color: #f92672">@</span><span style="color: #f8f8f2">error</span><span style="color: #f92672">(</span><span style="color: #960050; background-color: #1e0010">&#39;</span><span style="color: #f8f8f2">image</span><span style="color: #960050; background-color: #1e0010">&#39;</span><span style="color: #f92672">)</span>            
                            <span style="color: #f92672">&lt;</span><span style="color: #f8f8f2">strong</span> <span style="color: #f8f8f2">style</span><span style="color: #f92672">=</span><span style="color: #e6db74">&quot;color: red;&quot;</span><span style="color: #f92672">&gt;{{</span> <span style="color: #960050; background-color: #1e0010">$</span><span style="color: #f8f8f2">message</span> <span style="color: #f92672">}}&lt;/</span><span style="color: #f8f8f2">strong</span><span style="color: #f92672">&gt;</span>
                    <span style="color: #f92672">@</span><span style="color: #f8f8f2">enderror</span>
                <span style="color: #f92672">&lt;/</span><span style="color: #f8f8f2">div</span><span style="color: #f92672">&gt;</span>

                <span style="color: #f92672">&lt;</span><span style="color: #f8f8f2">div</span> <span style="color: #f8f8f2">class</span><span style="color: #f92672">=</span><span style="color: #e6db74">&quot;row pt-4&quot;</span><span style="color: #f92672">&gt;</span>
                    <span style="color: #f92672">&lt;</span><span style="color: #f8f8f2">button</span> <span style="color: #f8f8f2">class</span><span style="color: #f92672">=</span><span style="color: #e6db74">&quot;btn btn-primary&quot;</span><span style="color: #f92672">&gt;</span><span style="color: #f8f8f2">Add</span> <span style="color: #f8f8f2">New</span> <span style="color: #f8f8f2">Post</span><span style="color: #f92672">&lt;/</span><span style="color: #f8f8f2">button</span><span style="color: #f92672">&gt;</span>
                <span style="color: #f92672">&lt;/</span><span style="color: #f8f8f2">div</span><span style="color: #f92672">&gt;</span>

            <span style="color: #f92672">&lt;/</span><span style="color: #f8f8f2">div</span><span style="color: #f92672">&gt;</span>
        <span style="color: #f92672">&lt;/</span><span style="color: #f8f8f2">div</span><span style="color: #f92672">&gt;</span>
    <span style="color: #f92672">&lt;/</span><span style="color: #f8f8f2">form</span><span style="color: #f92672">&gt;</span>
<span style="color: #f92672">&lt;/</span><span style="color: #f8f8f2">div</span><span style="color: #f92672">&gt;</span>
<span style="color: #f92672">@</span><span style="color: #f8f8f2">endsection</span>
</pre></div>
