<!-- HTML generated using hilite.me --><div style="background: #272822; overflow:auto;width:auto;border:none;border-width:.1em .1em .1em .8em;padding:.2em .6em;"><pre style="margin: 0; line-height: 125%"><span style="color: rgb(231, 95, 85)">&lt;section</span> <span style="color: #a6e22e">id=</span><span style="color: #e6db74">&quot;farm&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>

<span style="color: rgb(231, 95, 85)">&lt;div</span> <span style="color: #a6e22e">id=</span><span style="color: #e6db74">&quot;startAgain&quot;</span><span style="color: rgb(231, 95, 85)">&gt;&lt;a</span> <span style="color: #a6e22e">href=</span><span style="color: #e6db74">&quot;/index.html&quot;</span><span style="color: rgb(231, 95, 85)">&gt;&lt;button</span> <span style="color: #a6e22e">class=</span><span style="color: #e6db74">&quot;btn btn-success&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>Start Again<span style="color: rgb(231, 95, 85)">&lt;/button&gt;&lt;/a&gt;&lt;/div&gt;</span>

<span style="color: rgb(231, 95, 85)">&lt;div</span> <span style="color: #a6e22e">id=</span><span style="color: #e6db74">&quot;farmer2ndPg&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
  <span style="color: rgb(231, 95, 85)">&lt;div</span> <span style="color: #a6e22e">id=</span><span style="color: #e6db74">&quot;speech&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>
    <span style="color: rgb(231, 95, 85)">&lt;h4</span> <span style="color: #a6e22e">id=</span><span style="color: #e6db74">&quot;meet&quot;</span><span style="color: rgb(231, 95, 85)">&gt;</span>Look,<span style="color: rgb(231, 95, 85)">&lt;br&gt;</span> 
      <span style="color: rgb(231, 95, 85)">&lt;span</span> <span style="color: #a6e22e">id=</span><span style="color: #e6db74">&quot;theirName2&quot;</span> <span style="color: rgb(231, 95, 85)">&gt;&lt;/span&gt;&lt;br&gt;&lt;br&gt;</span> 
      <span style="color: rgb(231, 95, 85)">&lt;p&gt;&lt;/p&gt;</span>All my animals are running around! <span style="color: rgb(231, 95, 85)">&lt;br&gt;&lt;br&gt;</span> Which ones will we round up first?<span style="color: rgb(231, 95, 85)">&lt;/h4&gt;</span>
  <span style="color: rgb(231, 95, 85)">&lt;/div&gt;</span>
<span style="color: rgb(231, 95, 85)">&lt;/div&gt;</span>

<span style="color: rgb(231, 95, 85)">&lt;div</span> <span style="color: #a6e22e">id=</span><span style="color: #e6db74">&quot;cow&quot;</span><span style="color: rgb(231, 95, 85)">&gt;&lt;a</span> <span style="color: #a6e22e">id=</span><span style="color: #e6db74">&quot;cowLink&quot;</span> <span style="color: #a6e22e">href=</span><span style="color: #e6db74">&quot;/cow.html&quot;</span><span style="color: rgb(231, 95, 85)">&gt;&lt;/a&gt;&lt;/div&gt;</span>

<span style="color: rgb(231, 95, 85)">&lt;div</span> <span style="color: #a6e22e">id=</span><span style="color: #e6db74">&quot;horse&quot;</span><span style="color: rgb(231, 95, 85)">&gt;&lt;a</span> <span style="color: #a6e22e">id=</span><span style="color: #e6db74">&quot;horseLink&quot;</span> <span style="color: #a6e22e">href=</span><span style="color: #e6db74">&quot;/horse.html&quot;</span><span style="color: rgb(231, 95, 85)">&gt;&lt;/a&gt;&lt;/div&gt;</span>

<span style="color: rgb(231, 95, 85)">&lt;div</span> <span style="color: #a6e22e">id=</span><span style="color: #e6db74">&quot;chicken&quot;</span><span style="color: rgb(231, 95, 85)">&gt;&lt;a</span> <span style="color: #a6e22e">id=</span><span style="color: #e6db74">&quot;chickenLink&quot;</span> <span style="color: #a6e22e">href=</span><span style="color: #e6db74">&quot;/chicken.html&quot;</span><span style="color: rgb(231, 95, 85)">&gt;&lt;/a&gt;&lt;/div&gt;</span>

<span style="color: rgb(231, 95, 85)">&lt;div</span> <span style="color: #a6e22e">id=</span><span style="color: #e6db74">&quot;pig&quot;</span><span style="color: rgb(231, 95, 85)">&gt;&lt;a</span> <span style="color: #a6e22e">id=</span><span style="color: #e6db74">&quot;pigLink&quot;</span> <span style="color: #a6e22e">href=</span><span style="color: #e6db74">&quot;/pig.html&quot;</span><span style="color: rgb(231, 95, 85)">&gt;&lt;/a&gt;&lt;/div&gt;</span>
<span style="color: rgb(231, 95, 85)">&lt;div</span> <span style="color: #a6e22e">id=</span><span style="color: #e6db74">&quot;sheep&quot;</span><span style="color: rgb(231, 95, 85)">&gt;&lt;a</span> <span style="color: #a6e22e">id=</span><span style="color: #e6db74">&quot;sheepLink&quot;</span> <span style="color: #a6e22e">href=</span><span style="color: #e6db74">&quot;/sheep.html&quot;</span><span style="color: rgb(231, 95, 85)">&gt;&lt;/a&gt;&lt;/div&gt;</span>
<span style="color: rgb(231, 95, 85)">&lt;div</span> <span style="color: #a6e22e">id=</span><span style="color: #e6db74">&quot;donkey&quot;</span><span style="color: rgb(231, 95, 85)">&gt;&lt;a</span> <span style="color: #a6e22e">id=</span><span style="color: #e6db74">&quot;donkeyLink&quot;</span> <span style="color: #a6e22e">href=</span><span style="color: #e6db74">&quot;/donkey.html&quot;</span><span style="color: rgb(231, 95, 85)">&gt;&lt;/a&gt;&lt;/div&gt;</span>

</pre></div>
