<!-- HTML generated using hilite.me --><div style="background: #272822; overflow:auto;width:auto;border:solid gray;border-width:.1em .1em .1em .8em;padding:.2em .6em;"><pre style="margin: 0; line-height: 125%"><span style="color: #75715e">//SELECT THE CANVAS</span>
<span style="color: #66d9ef">const</span> <span style="color: #a6e22e">canvas</span> <span style="color: #f92672">=</span> <span style="color: #f8f8f2">document.</span><span style="color: #a6e22e">getElementById</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;pong&quot;</span><span style="color: #f8f8f2">);</span>
<span style="color: #66d9ef">const</span> <span style="color: #a6e22e">context</span> <span style="color: #f92672">=</span> <span style="color: #a6e22e">canvas</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">getContext</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;2d&quot;</span><span style="color: #f8f8f2">);</span>

<span style="color: #75715e">//CREATE THE USER PADDLE</span>
<span style="color: #66d9ef">const</span> <span style="color: #a6e22e">user</span> <span style="color: #f92672">=</span> <span style="color: #f8f8f2">{</span>
  <span style="color: #a6e22e">x</span><span style="color: #f92672">:</span> <span style="color: #ae81ff">30</span><span style="color: #f8f8f2">,</span>
  <span style="color: #a6e22e">y</span><span style="color: #f92672">:</span> <span style="color: #a6e22e">canvas</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">height</span> <span style="color: #f92672">/</span> <span style="color: #ae81ff">2</span> <span style="color: #f92672">-</span> <span style="color: #ae81ff">50</span><span style="color: #f8f8f2">,</span>
  <span style="color: #a6e22e">width</span><span style="color: #f92672">:</span> <span style="color: #ae81ff">20</span><span style="color: #f8f8f2">,</span>
  <span style="color: #a6e22e">height</span><span style="color: #f92672">:</span> <span style="color: #ae81ff">100</span><span style="color: #f8f8f2">,</span>
  <span style="color: #a6e22e">color</span><span style="color: #f92672">:</span> <span style="color: #e6db74">&quot;white&quot;</span><span style="color: #f8f8f2">,</span>
  <span style="color: #a6e22e">score</span><span style="color: #f92672">:</span> <span style="color: #ae81ff">0</span>
<span style="color: #f8f8f2">}</span>

<span style="color: #75715e">//CREATE THE COMPUTER PADDLE</span>
<span style="color: #66d9ef">const</span> <span style="color: #a6e22e">comp</span> <span style="color: #f92672">=</span> <span style="color: #f8f8f2">{</span>
  <span style="color: #a6e22e">x</span><span style="color: #f92672">:</span> <span style="color: #a6e22e">canvas</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">width</span> <span style="color: #f92672">-</span> <span style="color: #ae81ff">50</span><span style="color: #f8f8f2">,</span>
  <span style="color: #a6e22e">y</span><span style="color: #f92672">:</span> <span style="color: #a6e22e">canvas</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">height</span> <span style="color: #f92672">/</span> <span style="color: #ae81ff">2</span> <span style="color: #f92672">-</span> <span style="color: #ae81ff">50</span><span style="color: #f8f8f2">,</span>
  <span style="color: #a6e22e">width</span><span style="color: #f92672">:</span> <span style="color: #ae81ff">20</span><span style="color: #f8f8f2">,</span>
  <span style="color: #a6e22e">height</span><span style="color: #f92672">:</span> <span style="color: #ae81ff">100</span><span style="color: #f8f8f2">,</span>
  <span style="color: #a6e22e">color</span><span style="color: #f92672">:</span> <span style="color: #e6db74">&quot;white&quot;</span><span style="color: #f8f8f2">,</span>
  <span style="color: #a6e22e">score</span><span style="color: #f92672">:</span> <span style="color: #ae81ff">0</span>
<span style="color: #f8f8f2">}</span>

<span style="color: #75715e">//CREATE THE BALL</span>
<span style="color: #66d9ef">const</span> <span style="color: #a6e22e">ball</span> <span style="color: #f92672">=</span> <span style="color: #f8f8f2">{</span>
  <span style="color: #a6e22e">x</span><span style="color: #f92672">:</span> <span style="color: #a6e22e">canvas</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">width</span> <span style="color: #f92672">/</span> <span style="color: #ae81ff">2</span><span style="color: #f8f8f2">,</span>
  <span style="color: #a6e22e">y</span><span style="color: #f92672">:</span> <span style="color: #a6e22e">canvas</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">height</span> <span style="color: #f92672">/</span> <span style="color: #ae81ff">2</span><span style="color: #f8f8f2">,</span>
  <span style="color: #a6e22e">radius</span><span style="color: #f92672">:</span> <span style="color: #ae81ff">10</span><span style="color: #f8f8f2">,</span>
  <span style="color: #a6e22e">speed</span><span style="color: #f92672">:</span> <span style="color: #ae81ff">5</span><span style="color: #f8f8f2">,</span>
  <span style="color: #a6e22e">velocityX</span><span style="color: #f92672">:</span> <span style="color: #ae81ff">5</span><span style="color: #f8f8f2">,</span>
  <span style="color: #a6e22e">velocityY</span><span style="color: #f92672">:</span> <span style="color: #ae81ff">5</span><span style="color: #f8f8f2">,</span>
  <span style="color: #a6e22e">color</span><span style="color: #f92672">:</span> <span style="color: #e6db74">&quot;rgb(0, 183, 255)&quot;</span>
<span style="color: #f8f8f2">}</span>

<span style="color: #75715e">//CREATE THE NET</span>
<span style="color: #66d9ef">const</span> <span style="color: #a6e22e">net</span> <span style="color: #f92672">=</span> <span style="color: #f8f8f2">{</span>
  <span style="color: #a6e22e">x</span><span style="color: #f92672">:</span> <span style="color: #a6e22e">canvas</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">width</span> <span style="color: #f92672">/</span> <span style="color: #ae81ff">2</span> <span style="color: #f92672">-</span> <span style="color: #ae81ff">1</span><span style="color: #f8f8f2">,</span>
  <span style="color: #a6e22e">y</span><span style="color: #f92672">:</span> <span style="color: #ae81ff">0</span><span style="color: #f8f8f2">,</span>
  <span style="color: #a6e22e">width</span><span style="color: #f92672">:</span> <span style="color: #ae81ff">2</span><span style="color: #f8f8f2">,</span>
  <span style="color: #a6e22e">height</span><span style="color: #f92672">:</span> <span style="color: #ae81ff">10</span><span style="color: #f8f8f2">,</span>
  <span style="color: #a6e22e">color</span><span style="color: #f92672">:</span> <span style="color: #e6db74">&quot;white&quot;</span>
<span style="color: #f8f8f2">}</span>

<span style="color: #75715e">//DRAW RECTANGLES</span>
<span style="color: #66d9ef">function</span> <span style="color: #a6e22e">drawRect</span><span style="color: #f8f8f2">(</span><span style="color: #a6e22e">x</span><span style="color: #f8f8f2">,</span> <span style="color: #a6e22e">y</span><span style="color: #f8f8f2">,</span> <span style="color: #a6e22e">w</span><span style="color: #f8f8f2">,</span> <span style="color: #a6e22e">h</span><span style="color: #f8f8f2">,</span> <span style="color: #a6e22e">color</span><span style="color: #f8f8f2">)</span> <span style="color: #f8f8f2">{</span>
  <span style="color: #a6e22e">context</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">fillStyle</span> <span style="color: #f92672">=</span> <span style="color: #a6e22e">color</span><span style="color: #f8f8f2">;</span>
  <span style="color: #a6e22e">context</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">fillRect</span><span style="color: #f8f8f2">(</span><span style="color: #a6e22e">x</span><span style="color: #f8f8f2">,</span> <span style="color: #a6e22e">y</span><span style="color: #f8f8f2">,</span> <span style="color: #a6e22e">w</span><span style="color: #f8f8f2">,</span> <span style="color: #a6e22e">h</span><span style="color: #f8f8f2">);</span>
<span style="color: #f8f8f2">}</span>
<span style="color: #a6e22e">drawRect</span><span style="color: #f8f8f2">(</span><span style="color: #ae81ff">0</span><span style="color: #f8f8f2">,</span> <span style="color: #ae81ff">0</span><span style="color: #f8f8f2">,</span> <span style="color: #a6e22e">canvas</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">width</span><span style="color: #f8f8f2">,</span> <span style="color: #a6e22e">canvas</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">height</span><span style="color: #f8f8f2">,</span> <span style="color: #e6db74">&quot;black&quot;</span><span style="color: #f8f8f2">)</span>

<span style="color: #75715e">//DRAW THE NET</span>
<span style="color: #66d9ef">function</span> <span style="color: #a6e22e">drawNet</span><span style="color: #f8f8f2">()</span> <span style="color: #f8f8f2">{</span>
  <span style="color: #66d9ef">for</span> <span style="color: #f8f8f2">(</span><span style="color: #66d9ef">let</span> <span style="color: #a6e22e">i</span> <span style="color: #f92672">=</span> <span style="color: #ae81ff">0</span><span style="color: #f8f8f2">;</span> <span style="color: #a6e22e">i</span> <span style="color: #f92672">&lt;=</span> <span style="color: #a6e22e">canvas</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">height</span><span style="color: #f8f8f2">;</span> <span style="color: #a6e22e">i</span> <span style="color: #f92672">+=</span> <span style="color: #ae81ff">15</span><span style="color: #f8f8f2">)</span> <span style="color: #f8f8f2">{</span>
    <span style="color: #a6e22e">drawRect</span><span style="color: #f8f8f2">(</span><span style="color: #a6e22e">net</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">x</span><span style="color: #f8f8f2">,</span> <span style="color: #a6e22e">net</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">y</span> <span style="color: #f92672">+</span> <span style="color: #a6e22e">i</span><span style="color: #f8f8f2">,</span> <span style="color: #a6e22e">net</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">width</span><span style="color: #f8f8f2">,</span> <span style="color: #a6e22e">net</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">height</span><span style="color: #f8f8f2">,</span> <span style="color: #a6e22e">net</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">color</span><span style="color: #f8f8f2">);</span>
  <span style="color: #f8f8f2">}</span>
<span style="color: #f8f8f2">}</span>

<span style="color: #75715e">//DRAW CIRCLE</span>
<span style="color: #66d9ef">function</span> <span style="color: #a6e22e">drawCircle</span><span style="color: #f8f8f2">(</span><span style="color: #a6e22e">x</span><span style="color: #f8f8f2">,</span> <span style="color: #a6e22e">y</span><span style="color: #f8f8f2">,</span> <span style="color: #a6e22e">r</span><span style="color: #f8f8f2">,</span> <span style="color: #a6e22e">color</span><span style="color: #f8f8f2">)</span> <span style="color: #f8f8f2">{</span>
  <span style="color: #a6e22e">context</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">fillStyle</span> <span style="color: #f92672">=</span> <span style="color: #a6e22e">color</span><span style="color: #f8f8f2">;</span>
  <span style="color: #a6e22e">context</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">beginPath</span><span style="color: #f8f8f2">();</span>
  <span style="color: #a6e22e">context</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">arc</span><span style="color: #f8f8f2">(</span><span style="color: #a6e22e">x</span><span style="color: #f8f8f2">,</span> <span style="color: #a6e22e">y</span><span style="color: #f8f8f2">,</span> <span style="color: #a6e22e">r</span><span style="color: #f8f8f2">,</span> <span style="color: #ae81ff">0</span><span style="color: #f8f8f2">,</span> <span style="color: #f8f8f2">Math.</span><span style="color: #a6e22e">PI</span> <span style="color: #f92672">*</span> <span style="color: #ae81ff">2</span><span style="color: #f8f8f2">,</span> <span style="color: #66d9ef">false</span><span style="color: #f8f8f2">);</span>
  <span style="color: #a6e22e">context</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">closePath</span><span style="color: #f8f8f2">();</span>
  <span style="color: #a6e22e">context</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">fill</span><span style="color: #f8f8f2">();</span>
<span style="color: #f8f8f2">}</span>

<span style="color: #75715e">//DRAW START GAME</span>
<span style="color: #66d9ef">function</span> <span style="color: #a6e22e">startGame</span><span style="color: #f8f8f2">(</span><span style="color: #a6e22e">text</span><span style="color: #f8f8f2">,</span> <span style="color: #a6e22e">x</span><span style="color: #f8f8f2">,</span> <span style="color: #a6e22e">y</span><span style="color: #f8f8f2">,</span> <span style="color: #a6e22e">color</span><span style="color: #f8f8f2">)</span> <span style="color: #f8f8f2">{</span>
  <span style="color: #a6e22e">context</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">fillStyle</span> <span style="color: #f92672">=</span> <span style="color: #a6e22e">color</span><span style="color: #f8f8f2">;</span>
  <span style="color: #a6e22e">context</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">font</span> <span style="color: #f92672">=</span> <span style="color: #e6db74">&quot;45px Helvetica&quot;</span><span style="color: #f8f8f2">;</span>
  <span style="color: #a6e22e">context</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">fillText</span><span style="color: #f8f8f2">(</span><span style="color: #a6e22e">text</span><span style="color: #f8f8f2">,</span> <span style="color: #a6e22e">x</span><span style="color: #f8f8f2">,</span> <span style="color: #a6e22e">y</span><span style="color: #f8f8f2">);</span>
<span style="color: #f8f8f2">}</span>

<span style="color: #75715e">//DRAW TEXT</span>
<span style="color: #66d9ef">function</span> <span style="color: #a6e22e">drawText</span><span style="color: #f8f8f2">(</span><span style="color: #a6e22e">text</span><span style="color: #f8f8f2">,</span> <span style="color: #a6e22e">x</span><span style="color: #f8f8f2">,</span> <span style="color: #a6e22e">y</span><span style="color: #f8f8f2">,</span> <span style="color: #a6e22e">color</span><span style="color: #f8f8f2">)</span> <span style="color: #f8f8f2">{</span>
  <span style="color: #a6e22e">context</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">fillStyle</span> <span style="color: #f92672">=</span> <span style="color: #a6e22e">color</span><span style="color: #f8f8f2">;</span>
  <span style="color: #a6e22e">context</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">font</span> <span style="color: #f92672">=</span> <span style="color: #e6db74">&quot;45px Helvetica&quot;</span><span style="color: #f8f8f2">;</span>
  <span style="color: #a6e22e">context</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">fillText</span><span style="color: #f8f8f2">(</span><span style="color: #a6e22e">text</span><span style="color: #f8f8f2">,</span> <span style="color: #a6e22e">x</span><span style="color: #f8f8f2">,</span> <span style="color: #a6e22e">y</span><span style="color: #f8f8f2">);</span>
<span style="color: #f8f8f2">}</span>




<span style="color: #75715e">//RENDER THE GAME</span>
<span style="color: #66d9ef">function</span> <span style="color: #a6e22e">render</span><span style="color: #f8f8f2">()</span> <span style="color: #f8f8f2">{</span>
  <span style="color: #75715e">//CLEAR THE CANVAS</span>
  <span style="color: #a6e22e">drawRect</span><span style="color: #f8f8f2">(</span><span style="color: #ae81ff">0</span><span style="color: #f8f8f2">,</span> <span style="color: #ae81ff">0</span><span style="color: #f8f8f2">,</span> <span style="color: #a6e22e">canvas</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">width</span><span style="color: #f8f8f2">,</span> <span style="color: #a6e22e">canvas</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">height</span><span style="color: #f8f8f2">,</span> <span style="color: #e6db74">&quot;black&quot;</span><span style="color: #f8f8f2">);</span>

  <span style="color: #75715e">//DRAW THE NET</span>
  <span style="color: #a6e22e">drawNet</span><span style="color: #f8f8f2">();</span>

  <span style="color: #75715e">//DRAW SCORE</span>
  <span style="color: #a6e22e">drawText</span><span style="color: #f8f8f2">(</span><span style="color: #a6e22e">user</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">score</span><span style="color: #f8f8f2">,</span> <span style="color: #a6e22e">canvas</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">width</span> <span style="color: #f92672">/</span> <span style="color: #ae81ff">4</span><span style="color: #f8f8f2">,</span> <span style="color: #a6e22e">canvas</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">height</span> <span style="color: #f92672">/</span> <span style="color: #ae81ff">5</span><span style="color: #f8f8f2">,</span> <span style="color: #e6db74">&quot;white&quot;</span><span style="color: #f8f8f2">);</span>
  <span style="color: #a6e22e">drawText</span><span style="color: #f8f8f2">(</span><span style="color: #a6e22e">comp</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">score</span><span style="color: #f8f8f2">,</span> <span style="color: #ae81ff">3</span> <span style="color: #f92672">*</span> <span style="color: #a6e22e">canvas</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">width</span> <span style="color: #f92672">/</span> <span style="color: #ae81ff">4</span><span style="color: #f8f8f2">,</span> <span style="color: #a6e22e">canvas</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">height</span> <span style="color: #f92672">/</span> <span style="color: #ae81ff">5</span><span style="color: #f8f8f2">,</span> <span style="color: #e6db74">&quot;white&quot;</span><span style="color: #f8f8f2">);</span>

  <span style="color: #75715e">//DRAW USER AND COMP PADDLES</span>
  <span style="color: #a6e22e">drawRect</span><span style="color: #f8f8f2">(</span><span style="color: #a6e22e">user</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">x</span><span style="color: #f8f8f2">,</span> <span style="color: #a6e22e">user</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">y</span><span style="color: #f8f8f2">,</span> <span style="color: #a6e22e">user</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">width</span><span style="color: #f8f8f2">,</span> <span style="color: #a6e22e">user</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">height</span><span style="color: #f8f8f2">,</span> <span style="color: #a6e22e">user</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">color</span><span style="color: #f8f8f2">);</span>
  <span style="color: #a6e22e">drawRect</span><span style="color: #f8f8f2">(</span><span style="color: #a6e22e">comp</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">x</span><span style="color: #f8f8f2">,</span> <span style="color: #a6e22e">comp</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">y</span><span style="color: #f8f8f2">,</span> <span style="color: #a6e22e">comp</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">width</span><span style="color: #f8f8f2">,</span> <span style="color: #a6e22e">comp</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">height</span><span style="color: #f8f8f2">,</span> <span style="color: #a6e22e">comp</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">color</span><span style="color: #f8f8f2">);</span>

  <span style="color: #75715e">//DRAW THE BALL</span>
  <span style="color: #a6e22e">drawCircle</span><span style="color: #f8f8f2">(</span><span style="color: #a6e22e">ball</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">x</span><span style="color: #f8f8f2">,</span> <span style="color: #a6e22e">ball</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">y</span><span style="color: #f8f8f2">,</span> <span style="color: #a6e22e">ball</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">radius</span><span style="color: #f8f8f2">,</span> <span style="color: #a6e22e">ball</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">color</span><span style="color: #f8f8f2">);</span>
<span style="color: #f8f8f2">}</span>


<span style="color: #75715e">//CONTROL THE USER PADDLE</span>
<span style="color: #a6e22e">canvas</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">addEventListener</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;mousemove&quot;</span><span style="color: #f8f8f2">,</span> <span style="color: #a6e22e">movePaddle</span><span style="color: #f8f8f2">);</span>


<span style="color: #66d9ef">function</span> <span style="color: #a6e22e">movePaddle</span><span style="color: #f8f8f2">(</span><span style="color: #a6e22e">evt</span><span style="color: #f8f8f2">)</span> <span style="color: #f8f8f2">{</span>
  <span style="color: #66d9ef">let</span> <span style="color: #a6e22e">rect</span> <span style="color: #f92672">=</span> <span style="color: #a6e22e">canvas</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">getBoundingClientRect</span><span style="color: #f8f8f2">();</span>

  <span style="color: #a6e22e">user</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">y</span> <span style="color: #f92672">=</span> <span style="color: #a6e22e">evt</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">clientY</span> <span style="color: #f92672">-</span> <span style="color: #a6e22e">rect</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">top</span> <span style="color: #f92672">-</span> <span style="color: #a6e22e">user</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">height</span> <span style="color: #f92672">/</span> <span style="color: #ae81ff">2</span><span style="color: #f8f8f2">;</span>
<span style="color: #f8f8f2">}</span>

<span style="color: #75715e">//COLLISION DETECTION</span>
<span style="color: #66d9ef">function</span> <span style="color: #a6e22e">collision</span><span style="color: #f8f8f2">(</span><span style="color: #a6e22e">b</span><span style="color: #f8f8f2">,</span> <span style="color: #a6e22e">p</span><span style="color: #f8f8f2">)</span> <span style="color: #f8f8f2">{</span>
  <span style="color: #a6e22e">b</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">top</span> <span style="color: #f92672">=</span> <span style="color: #a6e22e">b</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">y</span> <span style="color: #f92672">-</span> <span style="color: #a6e22e">b</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">radius</span><span style="color: #f8f8f2">;</span>
  <span style="color: #a6e22e">b</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">bottom</span> <span style="color: #f92672">=</span> <span style="color: #a6e22e">b</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">y</span> <span style="color: #f92672">+</span> <span style="color: #a6e22e">b</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">radius</span><span style="color: #f8f8f2">;</span>
  <span style="color: #a6e22e">b</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">left</span> <span style="color: #f92672">=</span> <span style="color: #a6e22e">b</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">x</span> <span style="color: #f92672">-</span> <span style="color: #a6e22e">b</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">radius</span><span style="color: #f8f8f2">;</span>
  <span style="color: #a6e22e">b</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">right</span> <span style="color: #f92672">=</span> <span style="color: #a6e22e">b</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">x</span> <span style="color: #f92672">+</span> <span style="color: #a6e22e">b</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">radius</span><span style="color: #f8f8f2">;</span>

  <span style="color: #a6e22e">p</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">top</span> <span style="color: #f92672">=</span> <span style="color: #a6e22e">p</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">y</span><span style="color: #f8f8f2">;</span>
  <span style="color: #a6e22e">p</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">bottom</span> <span style="color: #f92672">=</span> <span style="color: #a6e22e">p</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">y</span> <span style="color: #f92672">+</span> <span style="color: #a6e22e">p</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">height</span><span style="color: #f8f8f2">;</span>
  <span style="color: #a6e22e">p</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">left</span> <span style="color: #f92672">=</span> <span style="color: #a6e22e">p</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">x</span><span style="color: #f8f8f2">;</span>
  <span style="color: #a6e22e">p</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">right</span> <span style="color: #f92672">=</span> <span style="color: #a6e22e">p</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">x</span> <span style="color: #f92672">+</span> <span style="color: #a6e22e">p</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">width</span><span style="color: #f8f8f2">;</span>

  <span style="color: #75715e">//(return) IF THE BELOW IS TRUE FIRE THIS FUNCTION</span>
  <span style="color: #66d9ef">return</span> <span style="color: #a6e22e">b</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">right</span> <span style="color: #f92672">&gt;</span> <span style="color: #a6e22e">p</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">left</span> <span style="color: #f92672">&amp;&amp;</span> <span style="color: #a6e22e">b</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">bottom</span> <span style="color: #f92672">&gt;</span> <span style="color: #a6e22e">p</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">top</span> <span style="color: #f92672">&amp;&amp;</span> <span style="color: #a6e22e">b</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">left</span> <span style="color: #f92672">&lt;</span> <span style="color: #a6e22e">p</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">right</span> <span style="color: #f92672">&amp;&amp;</span> <span style="color: #a6e22e">b</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">top</span> <span style="color: #f92672">&lt;</span> <span style="color: #a6e22e">p</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">bottom</span><span style="color: #f8f8f2">;</span>
<span style="color: #f8f8f2">}</span>

<span style="color: #75715e">//RESET ON SCORE </span>
<span style="color: #66d9ef">function</span> <span style="color: #a6e22e">resetBall</span><span style="color: #f8f8f2">()</span> <span style="color: #f8f8f2">{</span>
  <span style="color: #a6e22e">ball</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">x</span> <span style="color: #f92672">=</span> <span style="color: #a6e22e">canvas</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">width</span> <span style="color: #f92672">/</span> <span style="color: #ae81ff">2</span><span style="color: #f8f8f2">;</span>
  <span style="color: #a6e22e">ball</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">y</span> <span style="color: #f92672">=</span> <span style="color: #a6e22e">canvas</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">height</span> <span style="color: #f92672">/</span> <span style="color: #ae81ff">2</span><span style="color: #f8f8f2">;</span>
  <span style="color: #a6e22e">ball</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">speed</span> <span style="color: #f92672">=</span> <span style="color: #ae81ff">2</span><span style="color: #f8f8f2">;</span>
  <span style="color: #a6e22e">ball</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">velocityX</span> <span style="color: #f92672">=</span> <span style="color: #ae81ff">2</span><span style="color: #f8f8f2">;</span>
  <span style="color: #a6e22e">ball</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">velocityY</span> <span style="color: #f92672">=</span> <span style="color: #ae81ff">2</span><span style="color: #f8f8f2">;</span>
<span style="color: #f8f8f2">}</span>


<span style="color: #75715e">//STARTING GAME ON CLICK</span>
<span style="color: #f8f8f2">document.</span><span style="color: #a6e22e">getElementById</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;startGame&quot;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">onclick</span> <span style="color: #f92672">=</span> <span style="color: #66d9ef">function</span> <span style="color: #f8f8f2">()</span> <span style="color: #f8f8f2">{</span>
  <span style="color: #75715e">//HIDING THE START BUTTON AND CURSOR TO NORMAL</span>
  <span style="color: #f8f8f2">(</span><span style="color: #66d9ef">this</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">style</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">cssText</span> <span style="color: #f92672">=</span> <span style="color: #e6db74">&quot;display: none;&quot;</span><span style="color: #f8f8f2">;</span>
  <span style="color: #f8f8f2">document.</span><span style="color: #a6e22e">getElementById</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;moveMouse&quot;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">style</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">cssText</span> <span style="color: #f92672">=</span> <span style="color: #e6db74">&quot;display: none;&quot;</span><span style="color: #f8f8f2">;</span>

  <span style="color: #75715e">//UPDATE : POSITION, MOVEMENT, SCORE ETC...</span>
  <span style="color: #66d9ef">function</span> <span style="color: #a6e22e">update</span><span style="color: #f8f8f2">()</span> <span style="color: #f8f8f2">{</span>
    <span style="color: #a6e22e">ball</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">x</span> <span style="color: #f92672">+=</span> <span style="color: #a6e22e">ball</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">velocityX</span><span style="color: #f8f8f2">;</span>
    <span style="color: #a6e22e">ball</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">y</span> <span style="color: #f92672">+=</span> <span style="color: #a6e22e">ball</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">velocityY</span><span style="color: #f8f8f2">;</span>

    <span style="color: #75715e">//A SIMPLE AI TO CONTROL THE COMP PADDLE</span>
    <span style="color: #66d9ef">let</span> <span style="color: #a6e22e">computerLevel</span> <span style="color: #f92672">=</span> <span style="color: #ae81ff">0.1</span><span style="color: #f8f8f2">;</span>
    <span style="color: #a6e22e">comp</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">y</span> <span style="color: #f92672">+=</span> <span style="color: #f8f8f2">(</span><span style="color: #a6e22e">ball</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">y</span> <span style="color: #f92672">-</span> <span style="color: #f8f8f2">(</span><span style="color: #a6e22e">comp</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">y</span> <span style="color: #f92672">+</span> <span style="color: #a6e22e">comp</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">height</span> <span style="color: #f92672">/</span> <span style="color: #ae81ff">2</span><span style="color: #f8f8f2">))</span> <span style="color: #f92672">*</span> <span style="color: #a6e22e">computerLevel</span><span style="color: #f8f8f2">;</span>

    <span style="color: #66d9ef">if</span> <span style="color: #f8f8f2">(</span><span style="color: #a6e22e">ball</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">y</span> <span style="color: #f92672">+</span> <span style="color: #a6e22e">ball</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">radius</span> <span style="color: #f92672">&gt;</span> <span style="color: #a6e22e">canvas</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">height</span> <span style="color: #f92672">||</span> <span style="color: #a6e22e">ball</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">y</span> <span style="color: #f92672">-</span> <span style="color: #a6e22e">ball</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">radius</span> <span style="color: #f92672">&lt;</span> <span style="color: #ae81ff">0</span><span style="color: #f8f8f2">)</span> <span style="color: #f8f8f2">{</span>
      <span style="color: #a6e22e">ball</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">velocityY</span> <span style="color: #f92672">=</span> <span style="color: #f92672">-</span><span style="color: #a6e22e">ball</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">velocityY</span><span style="color: #f8f8f2">;</span>
    <span style="color: #f8f8f2">}</span>

    <span style="color: #75715e">//if the ball is less than the canvas width divided by 2 its &quot;user&quot; else &quot;computer&quot;</span>
    <span style="color: #66d9ef">let</span> <span style="color: #a6e22e">player</span> <span style="color: #f92672">=</span> <span style="color: #f8f8f2">(</span><span style="color: #a6e22e">ball</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">x</span> <span style="color: #f92672">&lt;</span> <span style="color: #a6e22e">canvas</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">width</span> <span style="color: #f92672">/</span> <span style="color: #ae81ff">2</span> <span style="color: #f92672">?</span> <span style="color: #a6e22e">user</span> <span style="color: #f92672">:</span> <span style="color: #a6e22e">comp</span><span style="color: #f8f8f2">);</span>


    <span style="color: #66d9ef">if</span> <span style="color: #f8f8f2">(</span><span style="color: #a6e22e">collision</span><span style="color: #f8f8f2">(</span><span style="color: #a6e22e">ball</span><span style="color: #f8f8f2">,</span> <span style="color: #a6e22e">player</span><span style="color: #f8f8f2">))</span> <span style="color: #f8f8f2">{</span>
      <span style="color: #a6e22e">ball</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">velocityX</span> <span style="color: #f92672">=</span> <span style="color: #f92672">-</span><span style="color: #a6e22e">ball</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">velocityX</span><span style="color: #f8f8f2">;</span>
      <span style="color: #75715e">//SEE WHERE THE BALL HIT THE PLAYER</span>
      <span style="color: #66d9ef">let</span> <span style="color: #a6e22e">collidePoint</span> <span style="color: #f92672">=</span> <span style="color: #a6e22e">ball</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">y</span> <span style="color: #f92672">-</span> <span style="color: #f8f8f2">(</span><span style="color: #a6e22e">player</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">y</span> <span style="color: #f92672">+</span> <span style="color: #a6e22e">player</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">height</span> <span style="color: #f92672">/</span> <span style="color: #ae81ff">2</span><span style="color: #f8f8f2">);</span>

      <span style="color: #75715e">//NORMALISATION</span>
      <span style="color: #a6e22e">collidePoint</span> <span style="color: #f92672">=</span> <span style="color: #a6e22e">collidePoint</span> <span style="color: #f92672">/</span> <span style="color: #f8f8f2">(</span><span style="color: #a6e22e">player</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">height</span> <span style="color: #f92672">/</span> <span style="color: #ae81ff">2</span><span style="color: #f8f8f2">);</span>

      <span style="color: #75715e">//CALCULATE ANGLE IN RADIAN</span>
      <span style="color: #66d9ef">let</span> <span style="color: #a6e22e">angleRad</span> <span style="color: #f92672">=</span> <span style="color: #a6e22e">collidePoint</span> <span style="color: #f92672">*</span> <span style="color: #f8f8f2">Math.</span><span style="color: #a6e22e">PI</span> <span style="color: #f92672">/</span> <span style="color: #ae81ff">4</span><span style="color: #f8f8f2">;</span>

      <span style="color: #75715e">// X DIRECTION OF THE BALL WHEN HIT - If the ball is hit on the left the direction is positive, else negitive</span>
      <span style="color: #66d9ef">let</span> <span style="color: #a6e22e">direction</span> <span style="color: #f92672">=</span> <span style="color: #f8f8f2">(</span><span style="color: #a6e22e">ball</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">x</span> <span style="color: #f92672">&lt;</span> <span style="color: #a6e22e">canvas</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">width</span> <span style="color: #f92672">/</span> <span style="color: #ae81ff">2</span><span style="color: #f8f8f2">)</span> <span style="color: #f92672">?</span> <span style="color: #ae81ff">1</span> <span style="color: #f92672">:</span> <span style="color: #f92672">-</span><span style="color: #ae81ff">1</span><span style="color: #f8f8f2">;</span>

      <span style="color: #75715e">//CHANGE VELOCITY X AND Y BASED ON ANGLE</span>
      <span style="color: #a6e22e">ball</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">velocityX</span> <span style="color: #f92672">=</span> <span style="color: #a6e22e">direction</span> <span style="color: #f92672">*</span> <span style="color: #a6e22e">ball</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">speed</span> <span style="color: #f92672">*</span> <span style="color: #f8f8f2">Math.</span><span style="color: #a6e22e">cos</span><span style="color: #f8f8f2">(</span><span style="color: #a6e22e">angleRad</span><span style="color: #f8f8f2">);</span>
      <span style="color: #a6e22e">ball</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">velocityY</span> <span style="color: #f92672">=</span> <span style="color: #a6e22e">ball</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">speed</span> <span style="color: #f92672">*</span> <span style="color: #f8f8f2">Math.</span><span style="color: #a6e22e">sin</span><span style="color: #f8f8f2">(</span><span style="color: #a6e22e">angleRad</span><span style="color: #f8f8f2">);</span>

      <span style="color: #75715e">//EVERY TIME THE BALL HITS A PADDLE WE INCREASE THE SPEED</span>
      <span style="color: #a6e22e">ball</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">speed</span> <span style="color: #f92672">+=</span> <span style="color: #ae81ff">1.5</span><span style="color: #f8f8f2">;</span>
    <span style="color: #f8f8f2">}</span>

    <span style="color: #66d9ef">if</span> <span style="color: #f8f8f2">(</span><span style="color: #a6e22e">ball</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">x</span> <span style="color: #f92672">-</span> <span style="color: #a6e22e">ball</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">radius</span> <span style="color: #f92672">&lt;</span> <span style="color: #ae81ff">0</span><span style="color: #f8f8f2">)</span> <span style="color: #f8f8f2">{</span>
      <span style="color: #75715e">//COMPUTER SCORES</span>
      <span style="color: #a6e22e">comp</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">score</span><span style="color: #f92672">++</span><span style="color: #f8f8f2">;</span>
      <span style="color: #a6e22e">resetBall</span><span style="color: #f8f8f2">();</span>
    <span style="color: #f8f8f2">}</span> <span style="color: #66d9ef">else</span> <span style="color: #66d9ef">if</span> <span style="color: #f8f8f2">(</span><span style="color: #a6e22e">ball</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">x</span> <span style="color: #f92672">+</span> <span style="color: #a6e22e">ball</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">radius</span> <span style="color: #f92672">&gt;</span> <span style="color: #a6e22e">canvas</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">width</span><span style="color: #f8f8f2">)</span> <span style="color: #f8f8f2">{</span>
      <span style="color: #75715e">//USER SCORES</span>
      <span style="color: #a6e22e">user</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">score</span><span style="color: #f92672">++</span><span style="color: #f8f8f2">;</span>
      <span style="color: #a6e22e">resetBall</span><span style="color: #f8f8f2">();</span>
    <span style="color: #f8f8f2">}</span>

  <span style="color: #f8f8f2">}</span>

  <span style="color: #75715e">//GAME START</span>
  <span style="color: #66d9ef">function</span> <span style="color: #a6e22e">game</span><span style="color: #f8f8f2">()</span> <span style="color: #f8f8f2">{</span>
    <span style="color: #a6e22e">update</span><span style="color: #f8f8f2">();</span>
    <span style="color: #a6e22e">render</span><span style="color: #f8f8f2">();</span>
  <span style="color: #f8f8f2">}</span>

  <span style="color: #75715e">//LOOP</span>
  <span style="color: #66d9ef">const</span> <span style="color: #a6e22e">framesPerSecond</span> <span style="color: #f92672">=</span> <span style="color: #ae81ff">50</span><span style="color: #f8f8f2">;</span>
  <span style="color: #a6e22e">setInterval</span><span style="color: #f8f8f2">(</span><span style="color: #a6e22e">game</span><span style="color: #f8f8f2">,</span> <span style="color: #ae81ff">1000</span> <span style="color: #f92672">/</span> <span style="color: #a6e22e">framesPerSecond</span><span style="color: #f8f8f2">);</span>

<span style="color: #f8f8f2">};</span>


<span style="color: #75715e">//TAKE ME TO THE HOME PAGE</span>
<span style="color: #f8f8f2">document.</span><span style="color: #a6e22e">getElementById</span><span style="color: #f8f8f2">(</span><span style="color: #e6db74">&quot;gamePageBtn&quot;</span><span style="color: #f8f8f2">).</span><span style="color: #a6e22e">onclick</span> <span style="color: #f92672">=</span> <span style="color: #66d9ef">function</span> <span style="color: #f8f8f2">()</span> <span style="color: #f8f8f2">{</span>
  <span style="color: #a6e22e">location</span><span style="color: #f8f8f2">.</span><span style="color: #a6e22e">href</span> <span style="color: #f92672">=</span> <span style="color: #e6db74">&quot;/home.php&quot;</span><span style="color: #f8f8f2">;</span>
<span style="color: #f8f8f2">};</span>
</pre></div>
